import Mathlib.Probability.Independence.ZeroOne
import Mathlib.Probability.Moments.Covariance
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Real
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut

/-!
# Chapter 14: Strong mixing (α-mixing) coefficients

This file formalizes the strong-mixing machinery of Hansen §14.12–§14.14: the α-dependence
coefficient of two σ-algebras, the past/future σ-algebras of a process, the strong-mixing
coefficients of a process, and two theorems about them. Strong-mixing coefficients are entirely
absent from Mathlib v4.29, so the whole development is built directly from the independence API
(`ProbabilityTheory.Indep`, `iIndepFun`, `indep_biSup_compl`) and the real-valued measure API
(`MeasureTheory.Measure.real`).

## Main declarations

* `ProbabilityTheory.alphaDep m₁ m₂ P` — the **α-dependence coefficient** of two σ-algebras
  `m₁ m₂ : MeasurableSpace Ω` under `P`, i.e. the supremum of `|P(A ∩ B) − P(A) · P(B)|` over
  events `A ∈ m₁`, `B ∈ m₂`. API: `alphaDep_nonneg`, `alphaDep_le_one`,
  `abs_measureReal_inter_sub_mul_le_alphaDep` (the defining bound), `alphaDep_mono` (monotone,
  i.e. *increasing*, in each σ-algebra argument), `alphaDep_comm`, `alphaDep_eq_zero_of_indep`.
* `ProbabilityTheory.pastSigma X t`, `ProbabilityTheory.futureSigma X t` — the σ-algebras
  generated by `{X s | s ≤ t}` and `{X s | t ≤ s}` respectively, with the monotonicity lemmas
  `comap_le_pastSigma`, `comap_le_futureSigma`, `pastSigma_mono`, `futureSigma_antitone`.
* `ProbabilityTheory.mixingCoeff X P ℓ` — the **strong-mixing coefficient** at lag `ℓ`, the
  supremum over `t` of `alphaDep (pastSigma X (t − ℓ)) (futureSigma X t) P`. API:
  `mixingCoeff_nonneg`, `mixingCoeff_le_one`, `alphaDep_le_mixingCoeff` (the defining bound),
  `mixingCoeff_antitone` (antitone in `ℓ`).
* `ProbabilityTheory.IsStrongMixing X P` — the process is strongly mixing, `mixingCoeff X P ℓ → 0`.

## Hansen theorem tags

* `ProbabilityTheory.mixingCoeff_comp_le` — **Hansen Theorem 14.12**: a finite-lag measurable
  transformation `Zₜ = φ(Xₜ, …, X_{t−q})` does not increase the mixing coefficients,
  `mixingCoeff Z P ℓ ≤ mixingCoeff X P (ℓ − q)` for `q ≤ ℓ`.
* `ProbabilityTheory.iid_mixingCoeff_eq_zero` and `ProbabilityTheory.iid_isStrongMixing` — the
  strong-mixing half of **Hansen Theorem 14.14**: an i.i.d. process has `mixingCoeff = 0` at every
  lag `ℓ ≥ 1`, hence is strongly mixing.
* `ProbabilityTheory.abs_covariance_le_alphaDep_of_bounded`,
  `ProbabilityTheory.integral_abs_condExp_sub_le_eLpNorm` /
  `ProbabilityTheory.integral_abs_condExp_le_eLpNorm`, and
  `ProbabilityTheory.abs_covariance_le_alphaDep_of_memLp` — the three **Hansen Theorem 14.13**
  covariance inequalities (bounded, conditional-expectation `Lᵖ`, and `Lʳ`×`Lᵠ` cases), proved by a
  truncation/Davydov argument in the `CovarianceInequalities` section.

The ergodic half of Theorem 14.14 is `IsErgodicProcess.of_iid` (Hansen Theorem 14.4, in
`HansenEconometrics.ErgodicTheory.PathShift`); it is cited by name only and not imported here. The
β-mixing (absolute regularity) coefficient used in the Theorem 14.26 deferral note is added in a
companion pass and is out of scope for this file.

The time index is `ℤ`. The value space `E` only needs `[MeasurableSpace E]`.
-/

open MeasureTheory Filter Topology

namespace ProbabilityTheory

variable {Ω E F : Type*} [MeasurableSpace Ω] [MeasurableSpace E]

/-! ### The α-dependence coefficient of two σ-algebras -/

/-- The set of dependence discrepancies `|P(A ∩ B) − P(A) · P(B)|` over events `A ∈ m₁`, `B ∈ m₂`.
The supremum of this set is the α-dependence coefficient `alphaDep`. -/
private def alphaDepSet (m₁ m₂ : MeasurableSpace Ω) {_mΩ : MeasurableSpace Ω} (P : Measure Ω) :
    Set ℝ :=
  {x : ℝ | ∃ A B, MeasurableSet[m₁] A ∧ MeasurableSet[m₂] B ∧
    x = |P.real (A ∩ B) - P.real A * P.real B|}

/-- **α-dependence coefficient (strong-mixing dependence) of two σ-algebras.** For
`m₁ m₂ : MeasurableSpace Ω` and a measure `P`, `alphaDep m₁ m₂ P` is the supremum over events
`A ∈ m₁`, `B ∈ m₂` of the dependence discrepancy `|P(A ∩ B) − P(A) · P(B)|`, where `P(·)` denotes
the real-valued measure `Measure.real`. This is Hansen's `α(m₁, m₂)` from §14.12; it vanishes
exactly when the two σ-algebras are (α-)independent. -/
noncomputable def alphaDep (m₁ m₂ : MeasurableSpace Ω) {_mΩ : MeasurableSpace Ω} (P : Measure Ω) :
    ℝ :=
  sSup (alphaDepSet m₁ m₂ P)

omit [MeasurableSpace Ω] in
/-- The α-dependence coefficient is nonnegative (it is a supremum of absolute values). -/
theorem alphaDep_nonneg (m₁ m₂ : MeasurableSpace Ω) {_mΩ : MeasurableSpace Ω} (P : Measure Ω) :
    0 ≤ alphaDep m₁ m₂ P := by
  apply Real.sSup_nonneg
  rintro x ⟨A, B, -, -, rfl⟩
  exact abs_nonneg _

omit [MeasurableSpace Ω] in
/-- For a probability measure, every dependence discrepancy is bounded by `1`. -/
private theorem abs_measureReal_inter_sub_mul_le_one {_mΩ : MeasurableSpace Ω} {P : Measure Ω}
    [IsProbabilityMeasure P] (A B : Set Ω) :
    |P.real (A ∩ B) - P.real A * P.real B| ≤ 1 := by
  have h1 : (0 : ℝ) ≤ P.real (A ∩ B) := measureReal_nonneg
  have h2 : P.real (A ∩ B) ≤ 1 := measureReal_le_one
  have h3 : (0 : ℝ) ≤ P.real A := measureReal_nonneg
  have h4 : P.real A ≤ 1 := measureReal_le_one
  have h5 : (0 : ℝ) ≤ P.real B := measureReal_nonneg
  have h6 : P.real B ≤ 1 := measureReal_le_one
  rw [abs_le]
  constructor <;> nlinarith

omit [MeasurableSpace Ω] in
/-- The dependence-discrepancy set is bounded above by `1` for a probability measure. -/
private theorem bddAbove_alphaDepSet (m₁ m₂ : MeasurableSpace Ω) {_mΩ : MeasurableSpace Ω}
    {P : Measure Ω} [IsProbabilityMeasure P] :
    BddAbove (alphaDepSet m₁ m₂ P) := by
  refine ⟨1, ?_⟩
  rintro x ⟨A, B, -, -, rfl⟩
  exact abs_measureReal_inter_sub_mul_le_one A B

omit [MeasurableSpace Ω] in
/-- The α-dependence coefficient of a probability measure is at most `1`. -/
theorem alphaDep_le_one (m₁ m₂ : MeasurableSpace Ω) {_mΩ : MeasurableSpace Ω} (P : Measure Ω)
    [IsProbabilityMeasure P] : alphaDep m₁ m₂ P ≤ 1 := by
  apply Real.sSup_le _ (by norm_num)
  rintro x ⟨A, B, -, -, rfl⟩
  exact abs_measureReal_inter_sub_mul_le_one A B

omit [MeasurableSpace Ω] in
/-- **The defining bound for `alphaDep`.** For any `m₁`-measurable `A` and `m₂`-measurable `B`, the
dependence discrepancy `|P(A ∩ B) − P(A) · P(B)|` is at most `alphaDep m₁ m₂ P`. This is the
workhorse used to feed concrete pairs of events into the coefficient. -/
theorem abs_measureReal_inter_sub_mul_le_alphaDep {_mΩ : MeasurableSpace Ω} {P : Measure Ω}
    [IsProbabilityMeasure P] {m₁ m₂ : MeasurableSpace Ω} {A B : Set Ω}
    (hA : MeasurableSet[m₁] A) (hB : MeasurableSet[m₂] B) :
    |P.real (A ∩ B) - P.real A * P.real B| ≤ alphaDep m₁ m₂ P :=
  le_csSup (bddAbove_alphaDepSet (P := P) m₁ m₂) ⟨A, B, hA, hB, rfl⟩

omit [MeasurableSpace Ω] in
/-- **Monotonicity of `alphaDep`.** Enlarging either σ-algebra can only enlarge the α-dependence
coefficient: `alphaDep` is monotone (increasing) in each σ-algebra argument. A larger σ-algebra
supplies more events to take the supremum over. -/
theorem alphaDep_mono {_mΩ : MeasurableSpace Ω} {P : Measure Ω} [IsProbabilityMeasure P]
    {m₁ m₁' m₂ m₂' : MeasurableSpace Ω} (h₁ : m₁ ≤ m₁') (h₂ : m₂ ≤ m₂') :
    alphaDep m₁ m₂ P ≤ alphaDep m₁' m₂' P := by
  refine csSup_le_csSup (bddAbove_alphaDepSet (P := P) m₁' m₂')
    ⟨0, ∅, ∅, @MeasurableSet.empty Ω m₁, @MeasurableSet.empty Ω m₂, by simp⟩ ?_
  rintro x ⟨A, B, hA, hB, rfl⟩
  exact ⟨A, B, h₁ A hA, h₂ B hB, rfl⟩

omit [MeasurableSpace Ω] in
/-- The α-dependence coefficient is symmetric in its two σ-algebra arguments. -/
theorem alphaDep_comm (m₁ m₂ : MeasurableSpace Ω) {_mΩ : MeasurableSpace Ω} (P : Measure Ω) :
    alphaDep m₁ m₂ P = alphaDep m₂ m₁ P := by
  unfold alphaDep
  congr 1
  ext x
  constructor <;>
  · rintro ⟨A, B, hA, hB, rfl⟩
    exact ⟨B, A, hB, hA, by rw [Set.inter_comm, mul_comm]⟩

omit [MeasurableSpace Ω] in
/-- **Independent σ-algebras have zero α-dependence.** If `m₁` and `m₂` are independent under `P`,
then `alphaDep m₁ m₂ P = 0`, since every discrepancy `P(A ∩ B) − P(A) · P(B)` vanishes. -/
theorem alphaDep_eq_zero_of_indep {m₁ m₂ : MeasurableSpace Ω} {_mΩ : MeasurableSpace Ω}
    {P : Measure Ω} (h : Indep m₁ m₂ P) : alphaDep m₁ m₂ P = 0 := by
  refine le_antisymm ?_ (alphaDep_nonneg m₁ m₂ P)
  apply Real.sSup_le _ le_rfl
  rintro x ⟨A, B, hA, hB, rfl⟩
  rw [Indep_iff] at h
  have hAB : P (A ∩ B) = P A * P B := h A B hA hB
  have hreal : P.real (A ∩ B) = P.real A * P.real B := by
    simp only [measureReal_def, hAB, ENNReal.toReal_mul]
  simp only [hreal, sub_self, abs_zero, le_refl]

/-! ### Past and future σ-algebras of a process -/

/-- The **past σ-algebra** of a process `X : ℤ → Ω → E` at time `t`: the σ-algebra generated by
the coordinates `{X s | s ≤ t}`. -/
@[reducible] def pastSigma (X : ℤ → Ω → E) (t : ℤ) : MeasurableSpace Ω :=
  ⨆ s ∈ {u : ℤ | u ≤ t}, MeasurableSpace.comap (X s) inferInstance

/-- The **future σ-algebra** of a process `X : ℤ → Ω → E` at time `t`: the σ-algebra generated by
the coordinates `{X s | t ≤ s}`. -/
@[reducible] def futureSigma (X : ℤ → Ω → E) (t : ℤ) : MeasurableSpace Ω :=
  ⨆ s ∈ {u : ℤ | t ≤ u}, MeasurableSpace.comap (X s) inferInstance

omit [MeasurableSpace Ω] in
/-- Each past coordinate `X s` (with `s ≤ t`) is measurable with respect to `pastSigma X t`. -/
theorem comap_le_pastSigma (X : ℤ → Ω → E) {s t : ℤ} (hst : s ≤ t) :
    MeasurableSpace.comap (X s) inferInstance ≤ pastSigma X t :=
  le_biSup (fun u => MeasurableSpace.comap (X u) inferInstance) hst

omit [MeasurableSpace Ω] in
/-- Each future coordinate `X s` (with `t ≤ s`) is measurable with respect to `futureSigma X t`. -/
theorem comap_le_futureSigma (X : ℤ → Ω → E) {s t : ℤ} (hst : t ≤ s) :
    MeasurableSpace.comap (X s) inferInstance ≤ futureSigma X t :=
  le_biSup (fun u => MeasurableSpace.comap (X u) inferInstance) hst

omit [MeasurableSpace Ω] in
/-- The past σ-algebra is monotone in time: `pastSigma X s ≤ pastSigma X t` for `s ≤ t`. -/
theorem pastSigma_mono (X : ℤ → Ω → E) {s t : ℤ} (hst : s ≤ t) :
    pastSigma X s ≤ pastSigma X t :=
  biSup_mono fun _ hu => le_trans hu hst

omit [MeasurableSpace Ω] in
/-- The future σ-algebra is antitone in time: `futureSigma X t ≤ futureSigma X s` for `s ≤ t`. -/
theorem futureSigma_antitone (X : ℤ → Ω → E) {s t : ℤ} (hst : s ≤ t) :
    futureSigma X t ≤ futureSigma X s :=
  biSup_mono fun _ hu => le_trans hst hu

/-! ### Comparison of past/future σ-algebras under finite-lag transformations -/

omit [MeasurableSpace Ω] in
/-- If `Z s = φ(X s, X (s−1), …, X (s−q))` is a fixed measurable function of the last `q + 1`
coordinates, then `Z s` is `pastSigma X t`-measurable whenever `s ≤ t`: the σ-algebra it generates
is contained in the past σ-algebra of `X` up to time `t`. -/
private theorem comap_finLagComp_le_pastSigma {q : ℕ} {φ : (Fin (q + 1) → E) → F}
    [MeasurableSpace F] (hφ : Measurable φ) (X : ℤ → Ω → E) {s t : ℤ} (hst : s ≤ t) :
    MeasurableSpace.comap (fun ω => φ (fun j : Fin (q + 1) => X (s - (j : ℤ)) ω)) inferInstance
      ≤ pastSigma X t := by
  have hcomp : (fun ω => φ (fun j : Fin (q + 1) => X (s - (j : ℤ)) ω))
      = φ ∘ (fun ω (j : Fin (q + 1)) => X (s - (j : ℤ)) ω) := rfl
  rw [hcomp, ← MeasurableSpace.comap_comp]
  refine le_trans (MeasurableSpace.comap_mono hφ.comap_le) ?_
  rw [MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  refine iSup_le fun j => ?_
  rw [MeasurableSpace.comap_comp]
  have hj0 : (0 : ℤ) ≤ (j : ℤ) := by positivity
  exact comap_le_pastSigma X (by omega)

omit [MeasurableSpace Ω] in
/-- If `Z s = φ(X s, X (s−1), …, X (s−q))` is a fixed measurable function of the last `q + 1`
coordinates, then `Z s` is `futureSigma X (t − q)`-measurable whenever `t ≤ s`: the earliest
coordinate it can depend on is `X (s − q) ≥ X (t − q)`. -/
private theorem comap_finLagComp_le_futureSigma {q : ℕ} {φ : (Fin (q + 1) → E) → F}
    [MeasurableSpace F] (hφ : Measurable φ) (X : ℤ → Ω → E) {s t : ℤ} (hst : t ≤ s) :
    MeasurableSpace.comap (fun ω => φ (fun j : Fin (q + 1) => X (s - (j : ℤ)) ω)) inferInstance
      ≤ futureSigma X (t - q) := by
  have hcomp : (fun ω => φ (fun j : Fin (q + 1) => X (s - (j : ℤ)) ω))
      = φ ∘ (fun ω (j : Fin (q + 1)) => X (s - (j : ℤ)) ω) := rfl
  rw [hcomp, ← MeasurableSpace.comap_comp]
  refine le_trans (MeasurableSpace.comap_mono hφ.comap_le) ?_
  rw [MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  refine iSup_le fun j => ?_
  rw [MeasurableSpace.comap_comp]
  have hj0 : (0 : ℤ) ≤ (j : ℤ) := by positivity
  have hjq : (j : ℤ) ≤ (q : ℤ) := by exact_mod_cast Fin.is_le j
  exact comap_le_futureSigma X (by omega)

/-! ### Strong-mixing coefficients -/

/-- The set of α-dependence values `alphaDep (pastSigma X (t − ℓ)) (futureSigma X t) P` over all
times `t`. The supremum of this set is the strong-mixing coefficient `mixingCoeff`. -/
private def mixingCoeffSet (X : ℤ → Ω → E) (P : Measure Ω) (ℓ : ℕ) : Set ℝ :=
  {y : ℝ | ∃ t : ℤ, y = alphaDep (pastSigma X (t - ℓ)) (futureSigma X t) P}

/-- **Strong-mixing (α-mixing) coefficient of a process at lag `ℓ`** (Hansen §14.12). It is the
supremum over all times `t` of the α-dependence between the past up to `t − ℓ` and the future from
`t` onwards, `alphaDep (pastSigma X (t − ℓ)) (futureSigma X t) P`. -/
noncomputable def mixingCoeff (X : ℤ → Ω → E) (P : Measure Ω) (ℓ : ℕ) : ℝ :=
  sSup (mixingCoeffSet X P ℓ)

/-- The strong-mixing coefficient is nonnegative. -/
theorem mixingCoeff_nonneg (X : ℤ → Ω → E) (P : Measure Ω) (ℓ : ℕ) :
    0 ≤ mixingCoeff X P ℓ := by
  apply Real.sSup_nonneg
  rintro y ⟨t, rfl⟩
  exact alphaDep_nonneg _ _ _

/-- The set of α-dependence values is bounded above by `1` for a probability measure. -/
private theorem bddAbove_mixingCoeffSet [IsProbabilityMeasure P] (X : ℤ → Ω → E) (ℓ : ℕ) :
    BddAbove (mixingCoeffSet X P ℓ) := by
  refine ⟨1, ?_⟩
  rintro y ⟨t, rfl⟩
  exact alphaDep_le_one _ _ _

/-- The strong-mixing coefficient of a probability measure is at most `1`. -/
theorem mixingCoeff_le_one [IsProbabilityMeasure P] (X : ℤ → Ω → E) (ℓ : ℕ) :
    mixingCoeff X P ℓ ≤ 1 := by
  apply Real.sSup_le _ (by norm_num)
  rintro y ⟨t, rfl⟩
  exact alphaDep_le_one _ _ _

/-- **The defining bound for `mixingCoeff`.** The α-dependence between the past up to `t − ℓ` and
the future from `t` is at most the mixing coefficient at lag `ℓ`, for every time `t`. -/
theorem alphaDep_le_mixingCoeff [IsProbabilityMeasure P] (X : ℤ → Ω → E) (ℓ : ℕ) (t : ℤ) :
    alphaDep (pastSigma X (t - ℓ)) (futureSigma X t) P ≤ mixingCoeff X P ℓ :=
  le_csSup (bddAbove_mixingCoeffSet X ℓ) ⟨t, rfl⟩

/-- **Strong-mixing coefficients are antitone in the lag.** As the gap `ℓ` between past and future
grows, the past σ-algebra shrinks, so the coefficient decreases: `mixingCoeff X P` is antitone. -/
theorem mixingCoeff_antitone [IsProbabilityMeasure P] (X : ℤ → Ω → E) :
    Antitone (mixingCoeff X P) := by
  intro ℓ ℓ' hℓ
  apply Real.sSup_le _ (mixingCoeff_nonneg X P ℓ)
  rintro y ⟨t, rfl⟩
  calc alphaDep (pastSigma X (t - (ℓ' : ℤ))) (futureSigma X t) P
      ≤ alphaDep (pastSigma X (t - (ℓ : ℤ))) (futureSigma X t) P :=
        alphaDep_mono (pastSigma_mono X (by omega)) le_rfl
    _ ≤ mixingCoeff X P ℓ := alphaDep_le_mixingCoeff X ℓ t

/-- **A process `X` is strongly mixing** (α-mixing) under `P` if its mixing coefficients tend to `0`
as the lag grows (Hansen §14.12). -/
def IsStrongMixing (X : ℤ → Ω → E) (P : Measure Ω) : Prop :=
  Tendsto (fun ℓ => mixingCoeff X P ℓ) atTop (𝓝 0)

/-! ### Hansen Theorem 14.12 — finite-lag transformations do not increase mixing -/

/-- **Hansen Theorem 14.12.** A finite-lag measurable transformation does not increase the
strong-mixing coefficients. If `Z t = φ(X t, X (t−1), …, X (t−q))` is a fixed measurable function
of the last `q + 1` coordinates of `X`, then for `q ≤ ℓ`,
`mixingCoeff Z P ℓ ≤ mixingCoeff X P (ℓ − q)`.

The proof is a pure σ-algebra comparison: `Z`'s past up to `t − ℓ` sits inside `X`'s past up to
`t − ℓ`, and `Z`'s future from `t` sits inside `X`'s future from `t − q`; then `alphaDep_mono`
and the reindexing `t − ℓ = (t − q) − (ℓ − q)` finish. -/
theorem mixingCoeff_comp_le [IsProbabilityMeasure P] {q : ℕ} {φ : (Fin (q + 1) → E) → F}
    [MeasurableSpace F] (hφ : Measurable φ) (X : ℤ → Ω → E) {ℓ : ℕ} (hℓ : q ≤ ℓ) :
    mixingCoeff (fun t ω => φ (fun j : Fin (q + 1) => X (t - (j : ℤ)) ω)) P ℓ
      ≤ mixingCoeff X P (ℓ - q) := by
  refine Real.sSup_le ?_ (mixingCoeff_nonneg X P (ℓ - q))
  rintro y ⟨t, rfl⟩
  have hpast : pastSigma (fun t ω => φ (fun j : Fin (q + 1) => X (t - (j : ℤ)) ω)) (t - ℓ)
      ≤ pastSigma X (t - ℓ) := iSup₂_le fun _ hs => comap_finLagComp_le_pastSigma hφ X hs
  have hfut : futureSigma (fun t ω => φ (fun j : Fin (q + 1) => X (t - (j : ℤ)) ω)) t
      ≤ futureSigma X (t - q) := iSup₂_le fun _ hs => comap_finLagComp_le_futureSigma hφ X hs
  refine le_trans (alphaDep_mono hpast hfut) ?_
  have hidx : t - (ℓ : ℤ) = (t - (q : ℤ)) - ((ℓ - q : ℕ) : ℤ) := by omega
  rw [hidx]
  exact alphaDep_le_mixingCoeff X (ℓ - q) (t - q)

/-! ### Hansen Theorem 14.14 (mixing half) — i.i.d. implies strong mixing -/

/-- **Hansen Theorem 14.14 (mixing half), pointwise form.** An i.i.d. process has vanishing
strong-mixing coefficient at every positive lag: `mixingCoeff Y P ℓ = 0` for `1 ≤ ℓ`.

Independence of the family `Y` makes the past σ-algebra up to `t − ℓ` independent of the future
σ-algebra from `t` (they are generated by the disjoint blocks `{s ≤ t − ℓ}` and `{t ≤ s}`, which
are disjoint precisely because `ℓ ≥ 1`); the α-dependence of independent σ-algebras is `0`. -/
theorem iid_mixingCoeff_eq_zero [IsProbabilityMeasure P] {Y : ℤ → Ω → E}
    (h_indep : iIndepFun Y P) (h_meas : ∀ t, Measurable (Y t)) {ℓ : ℕ} (hℓ : 1 ≤ ℓ) :
    mixingCoeff Y P ℓ = 0 := by
  refine le_antisymm ?_ (mixingCoeff_nonneg Y P ℓ)
  refine Real.sSup_le ?_ le_rfl
  rintro y ⟨t, rfl⟩
  have hindep : Indep (pastSigma Y (t - ℓ)) (futureSigma Y t) P := by
    have hii : iIndep (fun i => MeasurableSpace.comap (Y i) inferInstance) P :=
      (iIndepFun_iff_iIndep _ Y P).mp h_indep
    have hle : ∀ n, MeasurableSpace.comap (Y n) inferInstance ≤
        (inferInstance : MeasurableSpace Ω) := fun n => (h_meas n).comap_le
    have key := indep_biSup_compl hle hii {u : ℤ | u ≤ t - (ℓ : ℤ)}
    have h2 : futureSigma Y t ≤
        ⨆ n ∈ {u : ℤ | u ≤ t - (ℓ : ℤ)}ᶜ, MeasurableSpace.comap (Y n) inferInstance := by
      refine biSup_mono ?_
      intro u hu
      simp only [Set.mem_setOf_eq, Set.mem_compl_iff] at *
      omega
    rw [Indep_iff] at key ⊢
    intro A B hA hB
    exact key A B hA (h2 B hB)
  exact le_of_eq (alphaDep_eq_zero_of_indep hindep)

/-- **Hansen Theorem 14.14 (mixing half).** An i.i.d. process is strongly mixing: since its mixing
coefficients vanish for every lag `ℓ ≥ 1`, they trivially converge to `0`.

The ergodic half of Hansen Theorem 14.14 is `IsErgodicProcess.of_iid` (Hansen Theorem 14.4). -/
theorem iid_isStrongMixing [IsProbabilityMeasure P] {Y : ℤ → Ω → E}
    (h_indep : iIndepFun Y P) (h_meas : ∀ t, Measurable (Y t)) :
    IsStrongMixing Y P := by
  refine (tendsto_congr' ?_).mp tendsto_const_nhds
  filter_upwards [eventually_ge_atTop 1] with ℓ hℓ
  exact (iid_mixingCoeff_eq_zero h_indep h_meas hℓ).symm

/-! ### Hansen Theorem 14.13 — mixing covariance inequalities

The three covariance/conditional-expectation inequalities of Hansen §14.13, proved from the
conditional-expectation pull-out, tower and Jensen properties together with the defining bound
`abs_measureReal_inter_sub_mul_le_alphaDep`. The engine is a *sign-variable* argument
(`integral_abs_condExp_sub_le_two_mul`): for an `m`-measurable sign `η = ±1` of `E[U|m] − E[U]`,
`∫ |E[U|m] − E[U]| = cov(η, U)`, which splits into two indicator covariances.
-/

section CovarianceInequalities

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P : Measure Ω} [IsProbabilityMeasure P]
  {m₁ m₂ m : MeasurableSpace Ω}

/-- **Sign engine for Theorem 14.13.** Suppose every indicator covariance `cov[1_A, U]` over
`A ∈ m` is bounded by `b ≥ 0`. Then `∫ |E[U | m] − E[U]| ≤ 2 b`.

The proof takes the `m`-measurable sign variable `η` of `g := E[U | m] − E[U]` (so `η · g = |g|`
and `|η| ≤ 1`), uses the pull-out and tower properties to rewrite `∫ η · g = cov[η, U]`, and splits
`η = 1_{g>0} − 1_{g<0}` into two indicators. -/
private theorem integral_abs_condExp_sub_le_two_mul
    (hm : m ≤ mΩ) {U : Ω → ℝ} (hU : MemLp U 2 P) {b : ℝ}
    (hcov : ∀ A, MeasurableSet[m] A → |covariance (A.indicator (fun _ => 1)) U P| ≤ b) :
    ∫ ω, |(P[U | m]) ω - P[U]| ∂P ≤ 2 * b := by
  classical
  have hUint : Integrable U P := hU.integrable one_le_two
  set c : ℝ := P[U] with hc
  -- `g := E[U | m] − E[U]` is `m`-strongly-measurable.
  set g : Ω → ℝ := fun ω => (P[U | m]) ω - c with hg
  have hg_meas : StronglyMeasurable[m] g :=
    stronglyMeasurable_condExp.sub stronglyMeasurable_const
  have hg_measurable : Measurable[m] g := hg_meas.measurable
  set pos : Set Ω := {ω | 0 < g ω} with hpos
  set neg : Set Ω := {ω | g ω < 0} with hneg
  have hpos_m : MeasurableSet[m] pos := measurableSet_lt measurable_const hg_measurable
  have hneg_m : MeasurableSet[m] neg := measurableSet_lt hg_measurable measurable_const
  set η : Ω → ℝ := pos.indicator (fun _ => 1) - neg.indicator (fun _ => 1) with hη
  have hη_sm : StronglyMeasurable[m] η :=
    (stronglyMeasurable_const.indicator hpos_m).sub (stronglyMeasurable_const.indicator hneg_m)
  have hη_sm_amb : StronglyMeasurable[mΩ] η := hη_sm.mono hm
  -- pointwise: `η · g = |g|`.
  have hηg : ∀ ω, η ω * g ω = |g ω| := by
    intro ω
    simp only [hη, Pi.sub_apply, Set.indicator_apply, hpos, hneg, Set.mem_setOf_eq]
    rcases lt_trichotomy (g ω) 0 with h | h | h
    · rw [if_neg (not_lt.2 h.le), if_pos h]; simp [abs_of_neg h]
    · simp [h]
    · rw [if_pos h, if_neg (not_lt.2 h.le)]; simp [abs_of_pos h]
  -- `|η| ≤ 1`.
  have hη_bdd : ∀ ω, |η ω| ≤ 1 := by
    intro ω
    simp only [hη, Pi.sub_apply, Set.indicator_apply, hpos, hneg, Set.mem_setOf_eq]
    rcases lt_trichotomy (g ω) 0 with h | h | h
    · rw [if_neg (not_lt.2 h.le), if_pos h]; norm_num
    · simp [h]
    · rw [if_pos h, if_neg (not_lt.2 h.le)]; norm_num
  have hη_bdd_norm : ∀ ω, ‖η ω‖ ≤ 1 := fun ω => by rw [Real.norm_eq_abs]; exact hη_bdd ω
  have hηU_int : Integrable (fun ω => η ω * U ω) P :=
    hUint.bdd_mul hη_sm_amb.aestronglyMeasurable (Filter.Eventually.of_forall hη_bdd_norm)
  -- pull-out + tower: `∫ η · E[U|m] = ∫ η · U`.
  have hpull : ∫ ω, η ω * (P[U | m]) ω ∂P = ∫ ω, η ω * U ω ∂P := by
    have h1 : P[fun ω => η ω * U ω | m] =ᵐ[P] fun ω => η ω * (P[U | m]) ω :=
      condExp_mul_of_stronglyMeasurable_left hη_sm hηU_int hUint
    calc ∫ ω, η ω * (P[U | m]) ω ∂P
        = ∫ ω, (P[fun ω => η ω * U ω | m]) ω ∂P := (integral_congr_ae h1).symm
      _ = ∫ ω, η ω * U ω ∂P := integral_condExp hm
  -- `η ∈ L²`, and the two indicators are too.
  have hη_memLp : MemLp η 2 P := by
    refine MemLp.of_bound hη_sm_amb.aestronglyMeasurable 1 ?_
    exact Filter.Eventually.of_forall (fun ω => by simpa using hη_bdd ω)
  have hη_int : Integrable η P := hη_memLp.integrable one_le_two
  have hpos_memLp : MemLp (pos.indicator (fun _ => (1 : ℝ))) 2 P :=
    (memLp_const (1 : ℝ)).indicator (hm _ hpos_m)
  have hneg_memLp : MemLp (neg.indicator (fun _ => (1 : ℝ))) 2 P :=
    (memLp_const (1 : ℝ)).indicator (hm _ hneg_m)
  -- `∫ |g| = cov[η, U]`.
  have hstepA : ∫ ω, |g ω| ∂P = covariance η U P := by
    have hcondExp_int : Integrable (fun ω => η ω * (P[U | m]) ω) P :=
      integrable_condExp.bdd_mul hη_sm_amb.aestronglyMeasurable
        (Filter.Eventually.of_forall hη_bdd_norm)
    have hηc_int : Integrable (fun ω => η ω * c) P := hη_int.mul_const c
    rw [covariance_eq_sub hη_memLp hU]
    calc ∫ ω, |g ω| ∂P
        = ∫ ω, η ω * g ω ∂P := by simp_rw [hηg]
      _ = ∫ ω, (η ω * (P[U | m]) ω - η ω * c) ∂P := by
            refine integral_congr_ae (Filter.Eventually.of_forall (fun ω => ?_))
            simp only [hg]; ring
      _ = (∫ ω, η ω * (P[U | m]) ω ∂P) - ∫ ω, η ω * c ∂P :=
            integral_sub hcondExp_int hηc_int
      _ = (∫ ω, η ω * U ω ∂P) - (∫ ω, η ω ∂P) * c := by
            rw [hpull, integral_mul_const]
      _ = P[η * U] - P[η] * P[U] := by rw [hc]; rfl
  -- split `cov[η, U]` into the two indicator covariances.
  have hsplit : covariance η U P
      = covariance (pos.indicator (fun _ => (1 : ℝ))) U P
        - covariance (neg.indicator (fun _ => (1 : ℝ))) U P :=
    covariance_sub_left hpos_memLp hneg_memLp hU
  calc ∫ ω, |g ω| ∂P
      = covariance (pos.indicator (fun _ => (1 : ℝ))) U P
        - covariance (neg.indicator (fun _ => (1 : ℝ))) U P := by rw [hstepA, hsplit]
    _ ≤ |covariance (pos.indicator (fun _ => (1 : ℝ))) U P|
        + |covariance (neg.indicator (fun _ => (1 : ℝ))) U P| :=
          (le_abs_self _).trans (abs_sub _ _)
    _ ≤ b + b := add_le_add (hcov _ hpos_m) (hcov _ hneg_m)
    _ = 2 * b := by ring

/-- **Iterated-expectations identity.** For an `m`-measurable bounded `W` and `U ∈ L²`,
`cov[W, U] = ∫ W · (E[U | m] − E[U])`. This is the pull-out/tower computation underlying every
part of Theorem 14.13. -/
private theorem covariance_eq_integral_mul_condExp_sub (hm : m ≤ mΩ) {W U : Ω → ℝ}
    (hW : StronglyMeasurable[m] W) {D : ℝ} (hWbdd : ∀ᵐ ω ∂P, ‖W ω‖ ≤ D) (hU : MemLp U 2 P) :
    covariance W U P = ∫ ω, W ω * ((P[U | m]) ω - P[U]) ∂P := by
  have hWamb : StronglyMeasurable[mΩ] W := hW.mono hm
  have hUint : Integrable U P := hU.integrable one_le_two
  have hWmemLp : MemLp W 2 P := MemLp.of_bound hWamb.aestronglyMeasurable D hWbdd
  have hWint : Integrable W P := hWmemLp.integrable one_le_two
  have hWU_int : Integrable (fun ω => W ω * U ω) P :=
    hUint.bdd_mul hWamb.aestronglyMeasurable hWbdd
  have hpull : ∫ ω, W ω * (P[U | m]) ω ∂P = ∫ ω, W ω * U ω ∂P := by
    have h1 : P[fun ω => W ω * U ω | m] =ᵐ[P] fun ω => W ω * (P[U | m]) ω :=
      condExp_mul_of_stronglyMeasurable_left hW hWU_int hUint
    calc ∫ ω, W ω * (P[U | m]) ω ∂P
        = ∫ ω, (P[fun ω => W ω * U ω | m]) ω ∂P := (integral_congr_ae h1).symm
      _ = ∫ ω, W ω * U ω ∂P := integral_condExp hm
  have hWcond_int : Integrable (fun ω => W ω * (P[U | m]) ω) P :=
    integrable_condExp.bdd_mul hWamb.aestronglyMeasurable hWbdd
  have hWc_int : Integrable (fun ω => W ω * P[U]) P := hWint.mul_const _
  rw [covariance_eq_sub hWmemLp hU]
  symm
  calc ∫ ω, W ω * ((P[U | m]) ω - P[U]) ∂P
      = (∫ ω, W ω * (P[U | m]) ω ∂P) - ∫ ω, W ω * P[U] ∂P := by
        simp_rw [mul_sub]; rw [integral_sub hWcond_int hWc_int]
    _ = (∫ ω, W ω * U ω ∂P) - (∫ ω, W ω ∂P) * P[U] := by rw [hpull, integral_mul_const]
    _ = P[W * U] - P[W] * P[U] := rfl

/-- Covariance of two indicators is the dependence discrepancy `P(A ∩ B) − P(A)·P(B)`. -/
private theorem covariance_indicator {A B : Set Ω}
    (hA : MeasurableSet[mΩ] A) (hB : MeasurableSet[mΩ] B) :
    covariance (A.indicator (fun _ => 1)) (B.indicator (fun _ => 1)) P
      = P.real (A ∩ B) - P.real A * P.real B := by
  have hAm : MemLp (A.indicator (fun _ => (1 : ℝ))) 2 P := (memLp_const 1).indicator hA
  have hBm : MemLp (B.indicator (fun _ => (1 : ℝ))) 2 P := (memLp_const 1).indicator hB
  have hmul : (A.indicator (fun _ => (1 : ℝ))) * (B.indicator (fun _ => 1))
      = (A ∩ B).indicator (fun _ => 1) := by
    funext ω
    by_cases hA' : ω ∈ A <;> by_cases hB' : ω ∈ B <;>
      simp [hA', hB', Set.mem_inter_iff]
  have eX : P[A.indicator (fun _ => (1 : ℝ))] = P.real A := by
    show ∫ ω, A.indicator (fun _ => (1 : ℝ)) ω ∂P = P.real A
    rw [integral_indicator_const (μ := P) (1 : ℝ) hA, smul_eq_mul, mul_one]
  have eY : P[B.indicator (fun _ => (1 : ℝ))] = P.real B := by
    show ∫ ω, B.indicator (fun _ => (1 : ℝ)) ω ∂P = P.real B
    rw [integral_indicator_const (μ := P) (1 : ℝ) hB, smul_eq_mul, mul_one]
  have eXY : P[(A ∩ B).indicator (fun _ => (1 : ℝ))] = P.real (A ∩ B) := by
    show ∫ ω, (A ∩ B).indicator (fun _ => (1 : ℝ)) ω ∂P = P.real (A ∩ B)
    rw [integral_indicator_const (μ := P) (1 : ℝ) (hA.inter hB), smul_eq_mul, mul_one]
  rw [covariance_eq_sub hAm hBm, hmul, eX, eY, eXY]

/-- Base bound: `|cov[1_B, 1_A]| ≤ α(m₁, m₂)` for `B ∈ m₂`, `A ∈ m₁`. -/
private theorem abs_covariance_indicator_le (hm₁ : m₁ ≤ mΩ)
    (hm₂ : m₂ ≤ mΩ) {A B : Set Ω} (hA : MeasurableSet[m₁] A) (hB : MeasurableSet[m₂] B) :
    |covariance (B.indicator (fun _ => 1)) (A.indicator (fun _ => 1)) P|
      ≤ alphaDep m₁ m₂ P := by
  have hAmΩ : MeasurableSet[mΩ] A := hm₁ A hA
  have hBmΩ : MeasurableSet[mΩ] B := hm₂ B hB
  have key : covariance (B.indicator (fun _ => 1)) (A.indicator (fun _ => 1)) P
      = P.real (B ∩ A) - P.real B * P.real A := covariance_indicator hBmΩ hAmΩ
  rw [key, Set.inter_comm, mul_comm]
  exact abs_measureReal_inter_sub_mul_le_alphaDep (_mΩ := mΩ) (P := P) hA hB

/-- **Step L1.** For `A ∈ m₁` and an `m₂`-measurable `Z` with `|Z| ≤ C` (`C ≥ 0`),
`|cov[1_A, Z]| ≤ 2 C α(m₁, m₂)`. Writing `cov[1_A, Z] = ∫ Z · (E[1_A | m₂] − E[1_A])` and using
`∫ |E[1_A | m₂] − E[1_A]| ≤ 2 α` (the sign engine over the two-indicator base bound). -/
private theorem covariance_indicator_bdd_le (hm₁ : m₁ ≤ mΩ) (hm₂ : m₂ ≤ mΩ)
    {A : Set Ω} (hA : MeasurableSet[m₁] A) {Z : Ω → ℝ} (hZ : StronglyMeasurable[m₂] Z)
    {C : ℝ} (hC : 0 ≤ C) (hZbdd : ∀ᵐ ω ∂P, |Z ω| ≤ C) :
    |covariance (A.indicator (fun _ => 1)) Z P| ≤ 2 * C * alphaDep m₁ m₂ P := by
  have hAmΩ : MeasurableSet[mΩ] A := hm₁ A hA
  have hAmemLp : MemLp (A.indicator (fun _ => (1 : ℝ))) 2 P := (memLp_const 1).indicator hAmΩ
  have hZamb : StronglyMeasurable[mΩ] Z := hZ.mono hm₂
  have hZbdd_norm : ∀ᵐ ω ∂P, ‖Z ω‖ ≤ C := by
    filter_upwards [hZbdd] with ω h; rwa [Real.norm_eq_abs]
  have hcovZ : covariance (A.indicator (fun _ => 1)) Z P
      = ∫ ω, Z ω * ((P[A.indicator (fun _ => (1 : ℝ)) | m₂]) ω
        - P[A.indicator (fun _ => (1 : ℝ))]) ∂P := by
    rw [covariance_comm]
    exact covariance_eq_integral_mul_condExp_sub hm₂ hZ hZbdd_norm hAmemLp
  have hEV : ∫ ω, |(P[A.indicator (fun _ => (1 : ℝ)) | m₂]) ω
      - P[A.indicator (fun _ => (1 : ℝ))]| ∂P ≤ 2 * alphaDep m₁ m₂ P :=
    integral_abs_condExp_sub_le_two_mul hm₂ hAmemLp
      (fun B hB => abs_covariance_indicator_le hm₁ hm₂ hA hB)
  have hVint : Integrable (fun ω => (P[A.indicator (fun _ => (1 : ℝ)) | m₂]) ω
      - P[A.indicator (fun _ => (1 : ℝ))]) P := integrable_condExp.sub (integrable_const _)
  have hZV_int : Integrable (fun ω => Z ω * ((P[A.indicator (fun _ => (1 : ℝ)) | m₂]) ω
      - P[A.indicator (fun _ => (1 : ℝ))])) P :=
    hVint.bdd_mul hZamb.aestronglyMeasurable hZbdd_norm
  calc |covariance (A.indicator (fun _ => 1)) Z P|
      = |∫ ω, Z ω * ((P[A.indicator (fun _ => (1 : ℝ)) | m₂]) ω
          - P[A.indicator (fun _ => (1 : ℝ))]) ∂P| := by rw [hcovZ]
    _ ≤ ∫ ω, |Z ω * ((P[A.indicator (fun _ => (1 : ℝ)) | m₂]) ω
          - P[A.indicator (fun _ => (1 : ℝ))])| ∂P := abs_integral_le_integral_abs
    _ ≤ ∫ ω, C * |(P[A.indicator (fun _ => (1 : ℝ)) | m₂]) ω
          - P[A.indicator (fun _ => (1 : ℝ))]| ∂P := by
        apply integral_mono_ae hZV_int.abs (hVint.abs.const_mul C)
        filter_upwards [hZbdd] with ω h
        rw [abs_mul]
        exact mul_le_mul_of_nonneg_right h (abs_nonneg _)
    _ = C * ∫ ω, |(P[A.indicator (fun _ => (1 : ℝ)) | m₂]) ω
          - P[A.indicator (fun _ => (1 : ℝ))]| ∂P := integral_const_mul C _
    _ ≤ C * (2 * alphaDep m₁ m₂ P) := mul_le_mul_of_nonneg_left hEV hC
    _ = 2 * C * alphaDep m₁ m₂ P := by ring

/-- **Bounded conditional-expectation bound.** For an `m₂`-measurable `Z` with `|Z| ≤ C` (`C ≥ 0`),
`∫ |E[Z | m₁] − E[Z]| ≤ 4 C α(m₁, m₂)`. The sign engine over `L1` (`covariance_indicator_bdd_le`).
-/
private theorem integral_abs_condExp_sub_le_bounded (hm₁ : m₁ ≤ mΩ) (hm₂ : m₂ ≤ mΩ)
    {Z : Ω → ℝ} (hZ : StronglyMeasurable[m₂] Z) {C : ℝ} (hC : 0 ≤ C)
    (hZbdd : ∀ᵐ ω ∂P, |Z ω| ≤ C) :
    ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P ≤ 4 * C * alphaDep m₁ m₂ P := by
  have hZamb : StronglyMeasurable[mΩ] Z := hZ.mono hm₂
  have hZbdd_norm : ∀ᵐ ω ∂P, ‖Z ω‖ ≤ C := by
    filter_upwards [hZbdd] with ω h; rwa [Real.norm_eq_abs]
  have hZmemLp : MemLp Z 2 P := MemLp.of_bound hZamb.aestronglyMeasurable C hZbdd_norm
  have h := integral_abs_condExp_sub_le_two_mul hm₁ hZmemLp
    (fun A hA => covariance_indicator_bdd_le hm₁ hm₂ hA hZ hC hZbdd)
  calc ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P
      ≤ 2 * (2 * C * alphaDep m₁ m₂ P) := h
    _ = 4 * C * alphaDep m₁ m₂ P := by ring

/-- **Hansen Theorem 14.13.1 (bounded case).** If `X` is `m₁`-measurable with `|X| ≤ C₁`, and `Z`
is `m₂`-measurable with `|Z| ≤ C₂` (both a.s., `C₁, C₂ ≥ 0`), then
`|cov[X, Z]| ≤ 4 C₁ C₂ α(m₁, m₂)`.

Route (Hansen §14.47): `cov[X, Z] = ∫ X · (E[Z | m₁] − E[Z])` by the iterated-expectations identity,
so `|cov[X, Z]| ≤ C₁ · ∫ |E[Z | m₁] − E[Z]| ≤ C₁ · 4 C₂ α`. -/
theorem abs_covariance_le_alphaDep_of_bounded (hm₁ : m₁ ≤ mΩ) (hm₂ : m₂ ≤ mΩ)
    {X Z : Ω → ℝ} (hX : StronglyMeasurable[m₁] X) (hZ : StronglyMeasurable[m₂] Z)
    {C₁ C₂ : ℝ} (hC₁ : 0 ≤ C₁) (hC₂ : 0 ≤ C₂)
    (hXbdd : ∀ᵐ ω ∂P, |X ω| ≤ C₁) (hZbdd : ∀ᵐ ω ∂P, |Z ω| ≤ C₂) :
    |covariance X Z P| ≤ 4 * C₁ * C₂ * alphaDep m₁ m₂ P := by
  have hXamb : StronglyMeasurable[mΩ] X := hX.mono hm₁
  have hZamb : StronglyMeasurable[mΩ] Z := hZ.mono hm₂
  have hXbdd_norm : ∀ᵐ ω ∂P, ‖X ω‖ ≤ C₁ := by
    filter_upwards [hXbdd] with ω h; rwa [Real.norm_eq_abs]
  have hZbdd_norm : ∀ᵐ ω ∂P, ‖Z ω‖ ≤ C₂ := by
    filter_upwards [hZbdd] with ω h; rwa [Real.norm_eq_abs]
  have hZmemLp : MemLp Z 2 P := MemLp.of_bound hZamb.aestronglyMeasurable C₂ hZbdd_norm
  have hcov : covariance X Z P = ∫ ω, X ω * ((P[Z | m₁]) ω - P[Z]) ∂P :=
    covariance_eq_integral_mul_condExp_sub hm₁ hX hXbdd_norm hZmemLp
  have hcore : ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P ≤ 4 * C₂ * alphaDep m₁ m₂ P :=
    integral_abs_condExp_sub_le_bounded hm₁ hm₂ hZ hC₂ hZbdd
  have hVint : Integrable (fun ω => (P[Z | m₁]) ω - P[Z]) P :=
    integrable_condExp.sub (integrable_const _)
  have hXV_int : Integrable (fun ω => X ω * ((P[Z | m₁]) ω - P[Z])) P :=
    hVint.bdd_mul hXamb.aestronglyMeasurable hXbdd_norm
  calc |covariance X Z P|
      = |∫ ω, X ω * ((P[Z | m₁]) ω - P[Z]) ∂P| := by rw [hcov]
    _ ≤ ∫ ω, |X ω * ((P[Z | m₁]) ω - P[Z])| ∂P := abs_integral_le_integral_abs
    _ ≤ ∫ ω, C₁ * |(P[Z | m₁]) ω - P[Z]| ∂P := by
        apply integral_mono_ae hXV_int.abs (hVint.abs.const_mul C₁)
        filter_upwards [hXbdd] with ω h
        rw [abs_mul]
        exact mul_le_mul_of_nonneg_right h (abs_nonneg _)
    _ = C₁ * ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P := integral_const_mul C₁ _
    _ ≤ C₁ * (4 * C₂ * alphaDep m₁ m₂ P) := mul_le_mul_of_nonneg_left hcore hC₁
    _ = 4 * C₁ * C₂ * alphaDep m₁ m₂ P := by ring

/-! #### Theorem 14.13, parts 3 and 2 — the `Lᵖ` covariance inequalities (Davydov route)

The bounded case above is upgraded to `Lᵖ` data by truncation. The truncation `Zb` of `Z` at level
`D` is bounded (so the bounded case applies to it), and the tail `Z − Zb` is controlled by a
Markov/Hölder moment bound. Optimizing `D` yields the `α^{1−1/r}` rate. Both parts carry the
hypothesis `0 < α(m₁, m₂)`: at `α = 0` the σ-algebras are independent and the bound is the
(separate) statement that the conditional expectation collapses to the mean, which we do not
formalize here. -/

/-- Pure real pointwise tail estimate. For `1 ≤ r` and `0 < D`, the truncation tail of a real number
`z` at level `D` is dominated by `D^{1−r} · |z|^r`. This is the pointwise seed of the Markov tail
bound `∫ |Z − Zb| ≤ D^{1−r} ∫ |Z|^r`. -/
private theorem abs_sub_trunc_le_rpow {r : ℝ} (hr : 1 ≤ r) {D : ℝ} (hD : 0 < D) (z : ℝ) :
    |z - (if |z| ≤ D then z else 0)| ≤ D ^ (1 - r) * |z| ^ r := by
  rcases le_or_gt (|z|) D with h | h
  · rw [if_pos h, sub_self, abs_zero]; positivity
  · rw [if_neg (not_le.2 h), sub_zero]
    have hz : 0 < |z| := lt_trans hD h
    have key : |z| = |z| ^ (1 - r) * |z| ^ r := by
      rw [← Real.rpow_add hz]; norm_num
    have hexp : |z| ^ (1 - r) ≤ D ^ (1 - r) :=
      Real.rpow_le_rpow_of_nonpos hD h.le (by linarith)
    conv_lhs => rw [key]
    exact mul_le_mul_of_nonneg_right hexp (Real.rpow_nonneg (abs_nonneg z) r)

/-- Pure real pointwise tail estimate, powered form. For `0 < s ≤ t` and `0 < D`, the `s`-th power
of the truncation tail of `z` at level `D` is dominated by `D^{s−t} · |z|^t`. This is the pointwise
seed of the Hölder tail bound `∫ |X − Xb|^{q'} ≤ D^{q'−r} ∫ |X|^r` used in Theorem 14.13.2. -/
private theorem abs_sub_trunc_rpow_le {s t : ℝ} (hs : 0 < s) (hst : s ≤ t) {D : ℝ} (hD : 0 < D)
    (z : ℝ) : |z - (if |z| ≤ D then z else 0)| ^ s ≤ D ^ (s - t) * |z| ^ t := by
  rcases le_or_gt (|z|) D with h | h
  · rw [if_pos h, sub_self, abs_zero, Real.zero_rpow hs.ne']; positivity
  · rw [if_neg (not_le.2 h), sub_zero]
    have hz : 0 < |z| := lt_trans hD h
    have key : |z| ^ s = |z| ^ (s - t) * |z| ^ t := by
      rw [← Real.rpow_add hz]; congr 1; ring
    have hexp : |z| ^ (s - t) ≤ D ^ (s - t) :=
      Real.rpow_le_rpow_of_nonpos hD h.le (by linarith)
    rw [key]
    exact mul_le_mul_of_nonneg_right hexp (Real.rpow_nonneg (abs_nonneg z) t)

/-- **Per-`D` truncation split** (no `Lᵖ` structure). For integrable `Z` and any `m₂`-measurable
`Zb` bounded by `D ≥ 0`, splitting `Z = Zb + (Z − Zb)` gives
`∫ |E[Z|m₁] − E[Z]| ≤ 4·D·α + 2·∫ |Z − Zb|`. The bounded part is
`integral_abs_condExp_sub_le_bounded` applied to `Zb`; the tail part uses the `L¹` contraction
`integral_abs_condExp_le` and Jensen for the mean. -/
private theorem integral_abs_condExp_sub_le_add_tail (hm₁ : m₁ ≤ mΩ) (hm₂ : m₂ ≤ mΩ)
    {Z Zb : Ω → ℝ} (hZint : Integrable Z P) (hZb : StronglyMeasurable[m₂] Zb)
    {D : ℝ} (hD : 0 ≤ D) (hZbdd : ∀ ω, |Zb ω| ≤ D) :
    ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P
      ≤ 4 * D * alphaDep m₁ m₂ P + 2 * ∫ ω, |Z ω - Zb ω| ∂P := by
  have hZbamb : StronglyMeasurable[mΩ] Zb := hZb.mono hm₂
  have hZbdd_norm : ∀ᵐ ω ∂P, ‖Zb ω‖ ≤ D :=
    Filter.Eventually.of_forall (fun ω => by rw [Real.norm_eq_abs]; exact hZbdd ω)
  have hZbmemLp : MemLp Zb 2 P := MemLp.of_bound hZbamb.aestronglyMeasurable D hZbdd_norm
  have hZbint : Integrable Zb P := hZbmemLp.integrable one_le_two
  set Zt : Ω → ℝ := fun ω => Z ω - Zb ω with hZt
  have hZtint : Integrable Zt P := hZint.sub hZbint
  have heqf : Zb + Zt = Z := by funext ω; simp only [Pi.add_apply, hZt]; ring
  have hce : P[Z | m₁] =ᵐ[P] (fun ω => (P[Zb | m₁]) ω + (P[Zt | m₁]) ω) := by
    rw [← heqf]; exact condExp_add hZbint hZtint m₁
  have hPZ : P[Z] = P[Zb] + P[Zt] := by rw [← heqf]; exact integral_add hZbint hZtint
  set A : Ω → ℝ := fun ω => (P[Zb | m₁]) ω - P[Zb] with hA
  set B : Ω → ℝ := fun ω => (P[Zt | m₁]) ω - P[Zt] with hB
  have hAint : Integrable A P := integrable_condExp.sub (integrable_const _)
  have hBint : Integrable B P := integrable_condExp.sub (integrable_const _)
  have hfae : (fun ω => (P[Z | m₁]) ω - P[Z]) =ᵐ[P] (fun ω => A ω + B ω) := by
    filter_upwards [hce] with ω hω
    simp only [hA, hB]; rw [hω, hPZ]; ring
  have hstep : ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P ≤ (∫ ω, |A ω| ∂P) + ∫ ω, |B ω| ∂P := by
    calc ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P
        = ∫ ω, |A ω + B ω| ∂P :=
          integral_congr_ae (by filter_upwards [hfae] with ω hω; rw [hω])
      _ ≤ ∫ ω, (|A ω| + |B ω|) ∂P :=
          integral_mono_ae (hAint.add hBint).abs (hAint.abs.add hBint.abs)
            (Filter.Eventually.of_forall (fun ω => abs_add_le _ _))
      _ = (∫ ω, |A ω| ∂P) + ∫ ω, |B ω| ∂P := integral_add hAint.abs hBint.abs
  have hAbound : ∫ ω, |A ω| ∂P ≤ 4 * D * alphaDep m₁ m₂ P := by
    have := integral_abs_condExp_sub_le_bounded (P := P) hm₁ hm₂ hZb hD
      (Filter.Eventually.of_forall hZbdd)
    simpa [hA] using this
  have hBbound : ∫ ω, |B ω| ∂P ≤ 2 * ∫ ω, |Zt ω| ∂P := by
    have hcontr : ∫ ω, |(P[Zt | m₁]) ω| ∂P ≤ ∫ ω, |Zt ω| ∂P := integral_abs_condExp_le Zt
    have hmean : |P[Zt]| ≤ ∫ ω, |Zt ω| ∂P := abs_integral_le_integral_abs
    calc ∫ ω, |B ω| ∂P
        ≤ ∫ ω, (|(P[Zt | m₁]) ω| + |P[Zt]|) ∂P :=
          integral_mono_ae hBint.abs (integrable_condExp.abs.add (integrable_const _))
            (Filter.Eventually.of_forall (fun ω => by
              simp only [hB, sub_eq_add_neg]
              exact (abs_add_le _ _).trans_eq (by rw [abs_neg])))
      _ = (∫ ω, |(P[Zt | m₁]) ω| ∂P) + |P[Zt]| := by
            rw [integral_add integrable_condExp.abs (integrable_const _),
              integral_const, probReal_univ, one_smul]
      _ ≤ (∫ ω, |Zt ω| ∂P) + ∫ ω, |Zt ω| ∂P := add_le_add hcontr hmean
      _ = 2 * ∫ ω, |Zt ω| ∂P := by ring
  calc ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P
      ≤ (∫ ω, |A ω| ∂P) + ∫ ω, |B ω| ∂P := hstep
    _ ≤ 4 * D * alphaDep m₁ m₂ P + 2 * ∫ ω, |Zt ω| ∂P := add_le_add hAbound hBbound
    _ = 4 * D * alphaDep m₁ m₂ P + 2 * ∫ ω, |Z ω - Zb ω| ∂P := by simp only [hZt]

/-- **Hansen Theorem 14.13.3 (general form).** The `Lᵖ` conditional-expectation bound of Davydov's
lemma. For `1 ≤ p < ∞`, `0 < α(m₁, m₂)`, and an `m₂`-measurable `Z ∈ Lᵖ`,
`∫ |E[Z | m₁] − E[Z]| ≤ 6 · ‖Z‖_p · α(m₁, m₂)^{1 − 1/p}`.
Truncating `Z` at the optimal level `D = ‖Z‖_p · α^{−1/p}` feeds the bounded case to the per-`D`
split; the Markov tail `∫ |Z − Zb| ≤ D^{1−p} ∫ |Z|^p` closes the gap, and substituting `D` collapses
both terms to the stated rate. This is stated without the centering `E[Z] = 0` that Hansen imposes
(see `integral_abs_condExp_le_eLpNorm` for that specialization). The hypothesis `0 < α` is a genuine
restriction (see the section docstring). -/
theorem integral_abs_condExp_sub_le_eLpNorm (hm₁ : m₁ ≤ mΩ) (hm₂ : m₂ ≤ mΩ)
    {p : ENNReal} (hp1 : 1 ≤ p) (hpt : p ≠ ⊤) (hα : 0 < alphaDep m₁ m₂ P)
    {Z : Ω → ℝ} (hZ : StronglyMeasurable[m₂] Z) (hZmem : MemLp Z p P) :
    ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P
      ≤ 6 * (eLpNorm Z p P).toReal * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹) := by
  have hp0 : p ≠ 0 := by rintro rfl; simp at hp1
  have hr1 : (1 : ℝ) ≤ p.toReal := by
    rw [← ENNReal.toReal_one]; exact ENNReal.toReal_mono hpt hp1
  have hr0 : (0 : ℝ) < p.toReal := lt_of_lt_of_le one_pos hr1
  have hrne : p.toReal ≠ 0 := hr0.ne'
  set M : ℝ := (eLpNorm Z p P).toReal with hM
  have hM0 : 0 ≤ M := by rw [hM]; exact ENNReal.toReal_nonneg
  -- moment identity: `Mᵖ = ∫ |Z|ᵖ` and integrability of `|Z|ᵖ`.
  have hZr : Integrable (fun ω => |Z ω| ^ p.toReal) P := by
    have h := hZmem.integrable_norm_rpow hp0 hpt
    simpa only [Real.norm_eq_abs] using h
  have hint_nonneg : 0 ≤ ∫ ω, ‖Z ω‖ ^ p.toReal ∂P :=
    integral_nonneg (fun ω => Real.rpow_nonneg (norm_nonneg _) _)
  have hMeq : M = (∫ ω, ‖Z ω‖ ^ p.toReal ∂P) ^ (p.toReal)⁻¹ := by
    rw [hM, MemLp.eLpNorm_eq_integral_rpow_norm hp0 hpt hZmem,
      ENNReal.toReal_ofReal (Real.rpow_nonneg hint_nonneg _)]
  have hMr : M ^ p.toReal = ∫ ω, |Z ω| ^ p.toReal ∂P := by
    rw [hMeq, ← Real.rpow_mul hint_nonneg, inv_mul_cancel₀ hrne, Real.rpow_one]
    simp only [Real.norm_eq_abs]
  rcases eq_or_lt_of_le hM0 with hM0eq | hMpos
  · -- `M = 0`: `Z =ᵐ 0`, so both sides vanish.
    have hen : eLpNorm Z p P = 0 := by
      have h : (eLpNorm Z p P).toReal = 0 := by rw [← hM, ← hM0eq]
      exact (ENNReal.toReal_eq_zero_iff _).mp h |>.resolve_right hZmem.2.ne
    have hZ0 : Z =ᵐ[P] 0 := (eLpNorm_eq_zero_iff (hZ.mono hm₂).aestronglyMeasurable hp0).mp hen
    have hPZ0 : P[Z] = 0 := by rw [integral_congr_ae hZ0]; simp
    have hcz : P[Z | m₁] =ᵐ[P] 0 := by
      have h := condExp_congr_ae (m := m₁) hZ0; rwa [condExp_zero] at h
    have hz : (fun ω => |(P[Z | m₁]) ω - P[Z]|) =ᵐ[P] 0 := by
      filter_upwards [hcz] with ω hω; simp [hω, hPZ0]
    have hMz : M = 0 := hM0eq.symm
    rw [integral_congr_ae hz, hMz]; simp
  · -- `0 < M`: the truncation argument.
    set D : ℝ := M * (alphaDep m₁ m₂ P) ^ (-(p.toReal)⁻¹) with hD_def
    have hDpos : 0 < D := mul_pos hMpos (Real.rpow_pos_of_pos hα _)
    set Zb : Ω → ℝ := fun ω => if |Z ω| ≤ D then Z ω else 0 with hZb_def
    have hset : MeasurableSet[m₂] {ω | |Z ω| ≤ D} :=
      measurableSet_le hZ.measurable.norm measurable_const
    have hZbsm : StronglyMeasurable[m₂] Zb := by
      have hZbeq : Zb = {ω | |Z ω| ≤ D}.indicator Z := by
        funext ω; simp only [hZb_def, Set.indicator_apply, Set.mem_setOf_eq]
      rw [hZbeq]; exact hZ.indicator hset
    have hZbdd : ∀ ω, |Zb ω| ≤ D := by
      intro ω
      by_cases h : |Z ω| ≤ D
      · simp only [hZb_def, if_pos h]; exact h
      · simp only [hZb_def, if_neg h, abs_zero]; exact hDpos.le
    have hsplit := integral_abs_condExp_sub_le_add_tail (P := P) hm₁ hm₂
      (hZmem.integrable hp1) hZbsm hDpos.le hZbdd
    -- Markov tail.
    have hZbint : Integrable Zb P :=
      (MemLp.of_bound (hZbsm.mono hm₂).aestronglyMeasurable D
        (Filter.Eventually.of_forall (fun ω => by rw [Real.norm_eq_abs]; exact hZbdd ω))).integrable
        one_le_two
    have htail : ∫ ω, |Z ω - Zb ω| ∂P
        ≤ D ^ (1 - p.toReal) * ∫ ω, |Z ω| ^ p.toReal ∂P := by
      rw [← integral_const_mul]
      refine integral_mono_ae ((hZmem.integrable hp1).sub hZbint).abs (hZr.const_mul _) ?_
      filter_upwards with ω
      simpa only [hZb_def] using abs_sub_trunc_le_rpow hr1 hDpos (Z ω)
    -- optimization at `D = M · α^(−1/p)`.
    have hα0 : (0 : ℝ) ≤ alphaDep m₁ m₂ P := hα.le
    have harn : (0 : ℝ) ≤ (alphaDep m₁ m₂ P) ^ (-(p.toReal)⁻¹) := Real.rpow_nonneg hα0 _
    have hE : -(p.toReal)⁻¹ * (1 - p.toReal) = 1 - (p.toReal)⁻¹ := by field_simp; ring
    have hfac1 : (alphaDep m₁ m₂ P) ^ (-(p.toReal)⁻¹) * alphaDep m₁ m₂ P
        = (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹) := by
      have h1 : (alphaDep m₁ m₂ P) ^ (-(p.toReal)⁻¹) * (alphaDep m₁ m₂ P) ^ (1 : ℝ)
          = (alphaDep m₁ m₂ P) ^ (-(p.toReal)⁻¹ + 1) := (Real.rpow_add hα _ _).symm
      rw [Real.rpow_one] at h1
      rw [h1]; congr 1; ring
    have hDpow : D ^ (1 - p.toReal)
        = M ^ (1 - p.toReal) * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹) := by
      rw [hD_def, Real.mul_rpow hM0 harn, ← Real.rpow_mul hα0, hE]
    have h1r : (1 - p.toReal) + p.toReal = 1 := by ring
    have hMpow : M ^ (1 - p.toReal) * M ^ p.toReal = M := by
      rw [← Real.rpow_add hMpos, h1r, Real.rpow_one]
    have ht1 : 4 * D * alphaDep m₁ m₂ P
        = 4 * (M * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹)) := by
      rw [hD_def, ← hfac1]; ring
    have ht2 : 2 * (D ^ (1 - p.toReal) * M ^ p.toReal)
        = 2 * (M * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹)) := by
      rw [hDpow,
        show M ^ (1 - p.toReal) * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹) * M ^ p.toReal
          = (M ^ (1 - p.toReal) * M ^ p.toReal) * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹) from by
            ring,
        hMpow]
    have hopt : 4 * D * alphaDep m₁ m₂ P + 2 * (D ^ (1 - p.toReal) * M ^ p.toReal)
        = 6 * M * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹) := by
      rw [ht1, ht2]; ring
    calc ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P
        ≤ 4 * D * alphaDep m₁ m₂ P + 2 * ∫ ω, |Z ω - Zb ω| ∂P := hsplit
      _ ≤ 4 * D * alphaDep m₁ m₂ P + 2 * (D ^ (1 - p.toReal) * ∫ ω, |Z ω| ^ p.toReal ∂P) := by
          have hstep2 : 2 * ∫ ω, |Z ω - Zb ω| ∂P
              ≤ 2 * (D ^ (1 - p.toReal) * ∫ ω, |Z ω| ^ p.toReal ∂P) := by
            apply mul_le_mul_of_nonneg_left htail; norm_num
          linarith [hstep2]
      _ = 4 * D * alphaDep m₁ m₂ P + 2 * (D ^ (1 - p.toReal) * M ^ p.toReal) := by rw [← hMr]
      _ = 6 * M * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹) := hopt

/-- **Hansen Theorem 14.13.3.** Davydov's `Lᵖ` bound for a *centered* variable: if `Z` is
`m₂`-measurable, `Z ∈ Lᵖ` with `1 ≤ p < ∞` and `E[Z] = 0`, and `0 < α(m₁, m₂)`, then
`∫ |E[Z | m₁]| ≤ 6 · ‖Z‖_p · α(m₁, m₂)^{1 − 1/p}`. Immediate from
`integral_abs_condExp_sub_le_eLpNorm` since centering collapses `E[Z | m₁] − E[Z]` to `E[Z | m₁]`.
-/
theorem integral_abs_condExp_le_eLpNorm (hm₁ : m₁ ≤ mΩ) (hm₂ : m₂ ≤ mΩ)
    {p : ENNReal} (hp1 : 1 ≤ p) (hpt : p ≠ ⊤) (hα : 0 < alphaDep m₁ m₂ P)
    {Z : Ω → ℝ} (hZ : StronglyMeasurable[m₂] Z) (hZmem : MemLp Z p P) (hZ0 : P[Z] = 0) :
    ∫ ω, |(P[Z | m₁]) ω| ∂P
      ≤ 6 * (eLpNorm Z p P).toReal * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹) := by
  have h := integral_abs_condExp_sub_le_eLpNorm hm₁ hm₂ hp1 hpt hα hZ hZmem
  simpa only [hZ0, sub_zero] using h

/-- **Bounded-left term of Theorem 14.13.2.** For an `m₁`-measurable `W` bounded by `D`, and an
`m₂`-measurable `Z ∈ Lᵖ`, the iterated-expectations pull-out plus Davydov's bound give
`|∫ W · (Z − E[Z])| ≤ D · 6 · ‖Z‖_p · α^{1 − 1/p}`. This is the truncated-`X` contribution to the
covariance inequality. -/
private theorem abs_integral_bdd_mul_sub_mean_le (hm₁ : m₁ ≤ mΩ) (hm₂ : m₂ ≤ mΩ)
    {p : ENNReal} (hp1 : 1 ≤ p) (hpt : p ≠ ⊤) (hα : 0 < alphaDep m₁ m₂ P)
    {W Z : Ω → ℝ} (hW : StronglyMeasurable[m₁] W) {D : ℝ} (hD : 0 ≤ D) (hWbdd : ∀ ω, |W ω| ≤ D)
    (hZ : StronglyMeasurable[m₂] Z) (hZmem : MemLp Z p P) :
    |∫ ω, W ω * (Z ω - P[Z]) ∂P|
      ≤ D * (6 * (eLpNorm Z p P).toReal * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹)) := by
  have hWamb : StronglyMeasurable[mΩ] W := hW.mono hm₁
  have hWbdd_norm : ∀ᵐ ω ∂P, ‖W ω‖ ≤ D :=
    Filter.Eventually.of_forall (fun ω => by rw [Real.norm_eq_abs]; exact hWbdd ω)
  have hZL1 : Integrable Z P := hZmem.integrable hp1
  have hWmemLp : MemLp W 2 P := MemLp.of_bound hWamb.aestronglyMeasurable D hWbdd_norm
  have hWint : Integrable W P := hWmemLp.integrable one_le_two
  have hWZ_int : Integrable (fun ω => W ω * Z ω) P :=
    hZL1.bdd_mul hWamb.aestronglyMeasurable hWbdd_norm
  have hWcond_int : Integrable (fun ω => W ω * (P[Z | m₁]) ω) P :=
    integrable_condExp.bdd_mul hWamb.aestronglyMeasurable hWbdd_norm
  have hWc_int : Integrable (fun ω => W ω * P[Z]) P := hWint.mul_const _
  -- pull-out + tower: `∫ W · E[Z|m₁] = ∫ W · Z`, hence `∫ W (Z−EZ) = ∫ W (E[Z|m₁]−EZ)`.
  have hpull0 : ∫ ω, W ω * (P[Z | m₁]) ω ∂P = ∫ ω, W ω * Z ω ∂P := by
    have h1 : P[fun ω => W ω * Z ω | m₁] =ᵐ[P] fun ω => W ω * (P[Z | m₁]) ω :=
      condExp_mul_of_stronglyMeasurable_left hW hWZ_int hZL1
    calc ∫ ω, W ω * (P[Z | m₁]) ω ∂P
        = ∫ ω, (P[fun ω => W ω * Z ω | m₁]) ω ∂P := (integral_congr_ae h1).symm
      _ = ∫ ω, W ω * Z ω ∂P := integral_condExp hm₁
  have hpull : ∫ ω, W ω * (Z ω - P[Z]) ∂P = ∫ ω, W ω * ((P[Z | m₁]) ω - P[Z]) ∂P := by
    calc ∫ ω, W ω * (Z ω - P[Z]) ∂P
        = (∫ ω, W ω * Z ω ∂P) - ∫ ω, W ω * P[Z] ∂P := by
            simp_rw [mul_sub]; exact integral_sub hWZ_int hWc_int
      _ = (∫ ω, W ω * (P[Z | m₁]) ω ∂P) - ∫ ω, W ω * P[Z] ∂P := by rw [hpull0]
      _ = ∫ ω, W ω * ((P[Z | m₁]) ω - P[Z]) ∂P := by
            simp_rw [mul_sub]; exact (integral_sub hWcond_int hWc_int).symm
  rw [hpull]
  have hVint : Integrable (fun ω => (P[Z | m₁]) ω - P[Z]) P :=
    integrable_condExp.sub (integrable_const _)
  have hWV_int : Integrable (fun ω => W ω * ((P[Z | m₁]) ω - P[Z])) P :=
    hVint.bdd_mul hWamb.aestronglyMeasurable hWbdd_norm
  have hcore : ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P
      ≤ 6 * (eLpNorm Z p P).toReal * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹) :=
    integral_abs_condExp_sub_le_eLpNorm hm₁ hm₂ hp1 hpt hα hZ hZmem
  calc |∫ ω, W ω * ((P[Z | m₁]) ω - P[Z]) ∂P|
      ≤ ∫ ω, |W ω * ((P[Z | m₁]) ω - P[Z])| ∂P := abs_integral_le_integral_abs
    _ ≤ ∫ ω, D * |(P[Z | m₁]) ω - P[Z]| ∂P := by
        apply integral_mono_ae hWV_int.abs (hVint.abs.const_mul D)
        filter_upwards with ω
        rw [abs_mul]
        exact mul_le_mul_of_nonneg_right (hWbdd ω) (abs_nonneg _)
    _ = D * ∫ ω, |(P[Z | m₁]) ω - P[Z]| ∂P := integral_const_mul D _
    _ ≤ D * (6 * (eLpNorm Z p P).toReal * (alphaDep m₁ m₂ P) ^ (1 - (p.toReal)⁻¹)) :=
        mul_le_mul_of_nonneg_left hcore hD

/-- **Centered covariance identity.** `cov[X, Z] = ∫ X · (Z − E[Z])`. Centering only the `Z` side
suffices because `∫ (Z − E[Z]) = 0` annihilates the `E[X]` term; the identity needs only that the
product `X · (Z − E[Z])` is integrable (guaranteed by Hölder when `1/r + 1/q ≤ 1`), not `L²`. -/
private theorem covariance_eq_integral_mul_sub_mean {X Z : Ω → ℝ}
    (hZL1 : Integrable Z P) (hXZc : Integrable (fun ω => X ω * (Z ω - P[Z])) P) :
    cov[X, Z; P] = ∫ ω, X ω * (Z ω - P[Z]) ∂P := by
  rw [covariance]
  have hEXc_int : Integrable (fun ω => P[X] * (Z ω - P[Z])) P :=
    (hZL1.sub (integrable_const _)).const_mul _
  have hzero : ∫ ω, (Z ω - P[Z]) ∂P = 0 := by
    rw [integral_sub hZL1 (integrable_const _), integral_const, probReal_univ, one_smul, sub_self]
  calc ∫ ω, (X ω - P[X]) * (Z ω - P[Z]) ∂P
      = ∫ ω, (X ω * (Z ω - P[Z]) - P[X] * (Z ω - P[Z])) ∂P := by
          apply integral_congr_ae; filter_upwards with ω; ring
    _ = (∫ ω, X ω * (Z ω - P[Z]) ∂P) - ∫ ω, P[X] * (Z ω - P[Z]) ∂P := integral_sub hXZc hEXc_int
    _ = (∫ ω, X ω * (Z ω - P[Z]) ∂P) - P[X] * ∫ ω, (Z ω - P[Z]) ∂P := by rw [integral_const_mul]
    _ = ∫ ω, X ω * (Z ω - P[Z]) ∂P := by rw [hzero, mul_zero, sub_zero]

/-- **Jensen `L¹ ≤ Lᵖ` bound** on a probability space. For `1 ≤ p` and `f ∈ Lᵖ`,
`∫ |f| ≤ (∫ |f|^p)^{1/p}`. Proved from `eLpNorm_le_eLpNorm_of_exponent_le` and the real-integral
form of the seminorm. -/
private theorem integral_abs_le_rpow_integral_abs_rpow {p : ℝ} (hp1 : 1 ≤ p) {f : Ω → ℝ}
    (hf : MemLp f (ENNReal.ofReal p) P) :
    ∫ ω, |f ω| ∂P ≤ (∫ ω, |f ω| ^ p ∂P) ^ p⁻¹ := by
  have hp0 : (0:ℝ) < p := lt_of_lt_of_le one_pos hp1
  have hle : (1 : ENNReal) ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp1
  have hf1 : MemLp f 1 P := hf.mono_exponent hle
  have hmono : eLpNorm f 1 P ≤ eLpNorm f (ENNReal.ofReal p) P :=
    eLpNorm_le_eLpNorm_of_exponent_le hle hf.1
  have hnn : ∀ s : ℝ, 0 ≤ ∫ ω, ‖f ω‖ ^ s ∂P :=
    fun s => integral_nonneg (fun ω => Real.rpow_nonneg (norm_nonneg _) _)
  have hL1 : (eLpNorm f 1 P).toReal = ∫ ω, |f ω| ∂P := by
    rw [MemLp.eLpNorm_eq_integral_rpow_norm one_ne_zero ENNReal.one_ne_top hf1,
      ENNReal.toReal_ofReal (Real.rpow_nonneg (hnn _) _)]
    simp only [ENNReal.toReal_one, Real.rpow_one, inv_one, Real.norm_eq_abs]
  have hLp : (eLpNorm f (ENNReal.ofReal p) P).toReal = (∫ ω, |f ω| ^ p ∂P) ^ p⁻¹ := by
    have hpne : ENNReal.ofReal p ≠ 0 := by
      simp only [Ne, ENNReal.ofReal_eq_zero, not_le]; exact hp0
    rw [MemLp.eLpNorm_eq_integral_rpow_norm hpne ENNReal.ofReal_ne_top hf,
      ENNReal.toReal_ofReal (Real.rpow_nonneg (hnn _) _), ENNReal.toReal_ofReal hp0.le]
    simp only [Real.norm_eq_abs]
  have hfin : eLpNorm f (ENNReal.ofReal p) P ≠ ⊤ := hf.2.ne
  have h := ENNReal.toReal_mono hfin hmono
  rwa [hL1, hLp] at h

/-- **Hölder tail term of Theorem 14.13.2.** For conjugate exponents `1/q' + 1/q = 1` (`q', q > 1`),
`f ∈ Lᵠ'` and `Z ∈ Lᵠ`, `|∫ f · (Z − E[Z])| ≤ 2 · ‖f‖_{q'} · ‖Z‖_q` (raw-moment norms). The mean is
split off and each piece is bounded by Hölder together with the Jensen `L¹ ≤ Lᵖ` bound. -/
private theorem abs_integral_mul_sub_mean_le_holder {q q' : ℝ} (hq : 1 < q) (hq' : 1 < q')
    (hqq' : q'⁻¹ + q⁻¹ = 1) {f Z : Ω → ℝ}
    (hf : MemLp f (ENNReal.ofReal q') P) (hZ : MemLp Z (ENNReal.ofReal q) P) :
    |∫ ω, f ω * (Z ω - P[Z]) ∂P|
      ≤ 2 * (∫ ω, |f ω| ^ q' ∂P) ^ q'⁻¹ * (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹ := by
  have hq0 : (0:ℝ) < q := by linarith
  have hq'0 : (0:ℝ) < q' := by linarith
  have hqE1 : (1:ENNReal) ≤ ENNReal.ofReal q := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hq.le
  have hq'E1 : (1:ENNReal) ≤ ENNReal.ofReal q' := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hq'.le
  have hfL1 : Integrable f P := hf.integrable hq'E1
  have hZL1 : Integrable Z P := hZ.integrable hqE1
  have hconj : q'.HolderConjugate q := Real.holderConjugate_iff.mpr ⟨hq', hqq'⟩
  haveI hHC : (ENNReal.ofReal q').HolderConjugate (ENNReal.ofReal q) := by
    rw [ENNReal.holderConjugate_iff, ← ENNReal.ofReal_inv_of_pos hq'0,
      ← ENNReal.ofReal_inv_of_pos hq0, ← ENNReal.ofReal_add (by positivity) (by positivity),
      hqq', ENNReal.ofReal_one]
  have hfZ_int : Integrable (fun ω => f ω * Z ω) P := hf.integrable_mul hZ
  have hfEZ_int : Integrable (fun ω => f ω * P[Z]) P := hfL1.mul_const _
  -- Jensen `L¹ ≤ Lᵖ` bounds and Hölder.
  have hJf : ∫ ω, |f ω| ∂P ≤ (∫ ω, |f ω| ^ q' ∂P) ^ q'⁻¹ :=
    integral_abs_le_rpow_integral_abs_rpow hq'.le hf
  have hJZ : ∫ ω, |Z ω| ∂P ≤ (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹ :=
    integral_abs_le_rpow_integral_abs_rpow hq.le hZ
  have hHolder : ∫ ω, |f ω| * |Z ω| ∂P
      ≤ (∫ ω, |f ω| ^ q' ∂P) ^ q'⁻¹ * (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹ := by
    have := integral_mul_le_Lp_mul_Lq_of_nonneg hconj
      (Filter.Eventually.of_forall (fun ω => abs_nonneg (f ω)))
      (Filter.Eventually.of_forall (fun ω => abs_nonneg (Z ω))) hf.abs hZ.abs
    simpa only [one_div] using this
  have hNf0 : 0 ≤ (∫ ω, |f ω| ^ q' ∂P) ^ q'⁻¹ :=
    Real.rpow_nonneg (integral_nonneg (fun ω => Real.rpow_nonneg (abs_nonneg _) _)) _
  have hNZ0 : 0 ≤ (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹ :=
    Real.rpow_nonneg (integral_nonneg (fun ω => Real.rpow_nonneg (abs_nonneg _) _)) _
  -- bound `|∫ f Z|` and `|E[Z]| · |∫ f|`.
  have hAZ : |∫ ω, f ω * Z ω ∂P| ≤ (∫ ω, |f ω| ^ q' ∂P) ^ q'⁻¹ * (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹ := by
    calc |∫ ω, f ω * Z ω ∂P|
        ≤ ∫ ω, |f ω * Z ω| ∂P := abs_integral_le_integral_abs
      _ = ∫ ω, |f ω| * |Z ω| ∂P := by simp_rw [abs_mul]
      _ ≤ _ := hHolder
  have hEZ : |P[Z]| ≤ (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹ :=
    (abs_integral_le_integral_abs).trans hJZ
  have hAf : |∫ ω, f ω ∂P| ≤ (∫ ω, |f ω| ^ q' ∂P) ^ q'⁻¹ :=
    (abs_integral_le_integral_abs).trans hJf
  have hkey : ∫ ω, f ω * (Z ω - P[Z]) ∂P
      = (∫ ω, f ω * Z ω ∂P) - (∫ ω, f ω ∂P) * P[Z] := by
    have he : (fun ω => f ω * (Z ω - P[Z])) = fun ω => f ω * Z ω - f ω * P[Z] := by
      funext ω; ring
    rw [he, integral_sub hfZ_int hfEZ_int, integral_mul_const]
  calc |∫ ω, f ω * (Z ω - P[Z]) ∂P|
      = |(∫ ω, f ω * Z ω ∂P) - (∫ ω, f ω ∂P) * P[Z]| := by rw [hkey]
    _ ≤ |∫ ω, f ω * Z ω ∂P| + |(∫ ω, f ω ∂P) * P[Z]| := by
        rw [sub_eq_add_neg]; exact (abs_add_le _ _).trans_eq (by rw [abs_neg])
    _ ≤ ((∫ ω, |f ω| ^ q' ∂P) ^ q'⁻¹ * (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹)
          + ((∫ ω, |f ω| ^ q' ∂P) ^ q'⁻¹ * (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹) := by
        apply add_le_add hAZ
        rw [abs_mul]
        exact mul_le_mul hAf hEZ (abs_nonneg _) hNf0
    _ = 2 * (∫ ω, |f ω| ^ q' ∂P) ^ q'⁻¹ * (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹ := by ring

/-- **Hansen Theorem 14.13.2.** Davydov's covariance inequality. For `1 < r`, `1 < q` with
`1/r + 1/q < 1`, an `m₁`-measurable `X ∈ Lʳ` and an `m₂`-measurable `Z ∈ Lᵠ`,
`|cov[X, Z]| ≤ 8 · ‖X‖_r · ‖Z‖_q · α(m₁, m₂)^{1 − 1/r − 1/q}`.
Truncate `X` at `D₁ = ‖X‖_r · α^{−1/r}`: the bounded part is bounded by Davydov's
conditional-expectation inequality (`abs_integral_bdd_mul_sub_mean_le`, constant 6), the tail by
Hölder against the conjugate exponent `q'` (`abs_integral_mul_sub_mean_le_holder`, constant 2);
substituting `D₁` collapses both to the stated rate. The hypothesis `0 < α` is inherited from part 3
(see the section docstring). -/
theorem abs_covariance_le_alphaDep_of_memLp (hm₁ : m₁ ≤ mΩ) (hm₂ : m₂ ≤ mΩ)
    (hα : 0 < alphaDep m₁ m₂ P) {r q : ℝ} (hr : 1 < r) (hq : 1 < q) (hrq : 1 / r + 1 / q < 1)
    {X Z : Ω → ℝ} (hX : StronglyMeasurable[m₁] X) (hZ : StronglyMeasurable[m₂] Z)
    (hXmem : MemLp X (ENNReal.ofReal r) P) (hZmem : MemLp Z (ENNReal.ofReal q) P) :
    |cov[X, Z; P]| ≤ 8 * (eLpNorm X (ENNReal.ofReal r) P).toReal
      * (eLpNorm Z (ENNReal.ofReal q) P).toReal
      * (alphaDep m₁ m₂ P) ^ (1 - r⁻¹ - q⁻¹) := by
  classical
  have hr0 : (0:ℝ) < r := by linarith
  have hq0 : (0:ℝ) < q := by linarith
  have hrne : r ≠ 0 := hr0.ne'
  have hqne : q ≠ 0 := hq0.ne'
  have hr1pos : (0:ℝ) < r - 1 := by linarith
  have hq1pos : (0:ℝ) < q - 1 := by linarith
  have hrq' : r⁻¹ + q⁻¹ < 1 := by rw [← one_div, ← one_div]; exact hrq
  have hqr_clear : q + r < r * q := by
    have h := hrq
    rw [div_add_div _ _ hrne hqne, div_lt_one (mul_pos hr0 hq0)] at h
    linarith
  have hrE1 : (1:ENNReal) ≤ ENNReal.ofReal r := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hr.le
  have hqE1 : (1:ENNReal) ≤ ENNReal.ofReal q := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hq.le
  have hrEne : ENNReal.ofReal r ≠ 0 := by simp only [Ne, ENNReal.ofReal_eq_zero, not_le]; exact hr0
  have hqEne : ENNReal.ofReal q ≠ 0 := by simp only [Ne, ENNReal.ofReal_eq_zero, not_le]; exact hq0
  have hrET : ENNReal.ofReal r ≠ ⊤ := ENNReal.ofReal_ne_top
  have hqET : ENNReal.ofReal q ≠ ⊤ := ENNReal.ofReal_ne_top
  have hrtoReal : (ENNReal.ofReal r).toReal = r := ENNReal.toReal_ofReal hr0.le
  have hqtoReal : (ENNReal.ofReal q).toReal = q := ENNReal.toReal_ofReal hq0.le
  have hXL1 : Integrable X P := hXmem.integrable hrE1
  have hZL1 : Integrable Z P := hZmem.integrable hqE1
  set MX : ℝ := (eLpNorm X (ENNReal.ofReal r) P).toReal with hMXdef
  set MZ : ℝ := (eLpNorm Z (ENNReal.ofReal q) P).toReal with hMZdef
  have hMX0 : 0 ≤ MX := ENNReal.toReal_nonneg
  have hMZ0 : 0 ≤ MZ := ENNReal.toReal_nonneg
  set r' : ℝ := r / (r - 1) with hr'def
  set q' : ℝ := q / (q - 1) with hq'def
  have hr'0 : 0 < r' := by rw [hr'def]; positivity
  have hq'0 : 0 < q' := by rw [hq'def]; positivity
  have hq'ne : q' ≠ 0 := hq'0.ne'
  have h1ltq' : 1 < q' := by rw [hq'def, lt_div_iff₀ hq1pos]; linarith
  have hq'inveq : q'⁻¹ = 1 - q⁻¹ := by rw [hq'def, inv_div]; field_simp
  have hr'inveq : r'⁻¹ = 1 - r⁻¹ := by rw [hr'def, inv_div]; field_simp
  have hqq'inv : q'⁻¹ + q⁻¹ = 1 := by rw [hq'inveq]; ring
  have hq'ler : q' ≤ r := by rw [hq'def, div_le_iff₀ hq1pos]; nlinarith [hqr_clear]
  have hr'leq : r' ≤ q := by rw [hr'def, div_le_iff₀ hr1pos]; nlinarith [hqr_clear]
  rcases eq_or_lt_of_le hMX0 with hMX0eq | hMXpos
  · -- `MX = 0` → `X =ᵐ 0` → covariance vanishes.
    have hen : eLpNorm X (ENNReal.ofReal r) P = 0 := by
      have h : (eLpNorm X (ENNReal.ofReal r) P).toReal = 0 := by rw [← hMXdef, ← hMX0eq]
      exact (ENNReal.toReal_eq_zero_iff _).mp h |>.resolve_right hXmem.2.ne
    have hX0 : X =ᵐ[P] 0 := (eLpNorm_eq_zero_iff (hX.mono hm₁).aestronglyMeasurable hrEne).mp hen
    have hcov0 : cov[X, Z; P] = 0 := by
      have hPX : P[X] = 0 := by rw [integral_congr_ae hX0]; simp
      have hz : (fun ω => (X ω - P[X]) * (Z ω - P[Z])) =ᵐ[P] 0 := by
        filter_upwards [hX0] with ω hω; simp [hω, hPX]
      rw [covariance, integral_congr_ae hz]; simp
    rw [hcov0, abs_zero, ← hMX0eq]; simp
  · -- `0 < MX`: truncation argument.
    have hXmoment_nonneg : 0 ≤ ∫ ω, |X ω| ^ r ∂P :=
      integral_nonneg (fun ω => Real.rpow_nonneg (abs_nonneg _) _)
    have hMXeq : MX = (∫ ω, |X ω| ^ r ∂P) ^ r⁻¹ := by
      rw [hMXdef, MemLp.eLpNorm_eq_integral_rpow_norm hrEne hrET hXmem, hrtoReal,
        ENNReal.toReal_ofReal (Real.rpow_nonneg (integral_nonneg
          (fun ω => Real.rpow_nonneg (norm_nonneg _) _)) _)]
      simp only [Real.norm_eq_abs]
    have hMXr : MX ^ r = ∫ ω, |X ω| ^ r ∂P := by
      rw [hMXeq, ← Real.rpow_mul hXmoment_nonneg, inv_mul_cancel₀ hrne, Real.rpow_one]
    have hMZeq : MZ = (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹ := by
      rw [hMZdef, MemLp.eLpNorm_eq_integral_rpow_norm hqEne hqET hZmem, hqtoReal,
        ENNReal.toReal_ofReal (Real.rpow_nonneg (integral_nonneg
          (fun ω => Real.rpow_nonneg (norm_nonneg _) _)) _)]
      simp only [Real.norm_eq_abs]
    -- truncation of `X` at the optimal level `D₁`.
    set D₁ : ℝ := MX * (alphaDep m₁ m₂ P) ^ (-(r⁻¹)) with hD₁def
    have hD₁pos : 0 < D₁ := mul_pos hMXpos (Real.rpow_pos_of_pos hα _)
    set Xb : Ω → ℝ := fun ω => if |X ω| ≤ D₁ then X ω else 0 with hXbdef
    have hset : MeasurableSet[m₁] {ω | |X ω| ≤ D₁} :=
      hX.norm.measurableSet_le stronglyMeasurable_const
    have hXb_sm : StronglyMeasurable[m₁] Xb := by
      have hXbeq : Xb = {ω | |X ω| ≤ D₁}.indicator X := by
        funext ω; simp only [hXbdef, Set.indicator_apply, Set.mem_setOf_eq]
      rw [hXbeq]; exact hX.indicator hset
    have hXbamb : StronglyMeasurable[mΩ] Xb := hXb_sm.mono hm₁
    have hXb_bdd : ∀ ω, |Xb ω| ≤ D₁ := by
      intro ω; by_cases h : |X ω| ≤ D₁
      · simp only [hXbdef, if_pos h]; exact h
      · simp only [hXbdef, if_neg h, abs_zero]; exact hD₁pos.le
    have hXb_bdd_norm : ∀ᵐ ω ∂P, ‖Xb ω‖ ≤ D₁ :=
      Filter.Eventually.of_forall (fun ω => by rw [Real.norm_eq_abs]; exact hXb_bdd ω)
    -- product integrability for the covariance identity via the conjugate `(r, r')`.
    haveI hHCr : (ENNReal.ofReal r).HolderConjugate (ENNReal.ofReal r') := by
      rw [ENNReal.holderConjugate_iff, ← ENNReal.ofReal_inv_of_pos hr0,
        ← ENNReal.ofReal_inv_of_pos hr'0, ← ENNReal.ofReal_add (by positivity) (by positivity),
        show r⁻¹ + r'⁻¹ = 1 from by rw [hr'inveq]; ring, ENNReal.ofReal_one]
    have hZc_mem : MemLp (fun ω => Z ω - P[Z]) (ENNReal.ofReal q) P := hZmem.sub (memLp_const _)
    have hZc_int : Integrable (fun ω => Z ω - P[Z]) P := hZL1.sub (integrable_const _)
    have hZc_r' : MemLp (fun ω => Z ω - P[Z]) (ENNReal.ofReal r') P :=
      hZc_mem.mono_exponent (ENNReal.ofReal_le_ofReal hr'leq)
    have hXZc_int : Integrable (fun ω => X ω * (Z ω - P[Z])) P := hXmem.integrable_mul hZc_r'
    have hcov_eq : cov[X, Z; P] = ∫ ω, X ω * (Z ω - P[Z]) ∂P :=
      covariance_eq_integral_mul_sub_mean hZL1 hXZc_int
    have hXbc_int : Integrable (fun ω => Xb ω * (Z ω - P[Z])) P :=
      hZc_int.bdd_mul hXbamb.aestronglyMeasurable hXb_bdd_norm
    have hXtc_int : Integrable (fun ω => (X ω - Xb ω) * (Z ω - P[Z])) P := by
      have he : (fun ω => (X ω - Xb ω) * (Z ω - P[Z]))
          = fun ω => X ω * (Z ω - P[Z]) - Xb ω * (Z ω - P[Z]) := by funext ω; ring
      rw [he]; exact hXZc_int.sub hXbc_int
    have hsplit_int : ∫ ω, X ω * (Z ω - P[Z]) ∂P
        = (∫ ω, Xb ω * (Z ω - P[Z]) ∂P) + ∫ ω, (X ω - Xb ω) * (Z ω - P[Z]) ∂P := by
      rw [← integral_add hXbc_int hXtc_int]
      apply integral_congr_ae; filter_upwards with ω; ring
    -- term A (bounded part).
    have hA := abs_integral_bdd_mul_sub_mean_le hm₁ hm₂ hqE1 hqET hα hXb_sm hD₁pos.le hXb_bdd
      hZ hZmem
    rw [hqtoReal, ← hMZdef] at hA
    have hAval : D₁ * (6 * MZ * (alphaDep m₁ m₂ P) ^ (1 - q⁻¹))
        = 6 * MX * MZ * (alphaDep m₁ m₂ P) ^ (1 - r⁻¹ - q⁻¹) := by
      rw [hD₁def,
        show MX * (alphaDep m₁ m₂ P) ^ (-(r⁻¹)) * (6 * MZ * (alphaDep m₁ m₂ P) ^ (1 - q⁻¹))
          = 6 * MX * MZ * ((alphaDep m₁ m₂ P) ^ (-(r⁻¹)) * (alphaDep m₁ m₂ P) ^ (1 - q⁻¹)) from by
            ring,
        ← Real.rpow_add hα, show (-(r⁻¹)) + (1 - q⁻¹) = 1 - r⁻¹ - q⁻¹ from by ring]
    -- term B (tail part) via Hölder.
    have hXq' : MemLp X (ENNReal.ofReal q') P :=
      hXmem.mono_exponent (ENNReal.ofReal_le_ofReal hq'ler)
    have hXbq' : MemLp Xb (ENNReal.ofReal q') P :=
      MemLp.of_bound hXbamb.aestronglyMeasurable D₁ hXb_bdd_norm
    have hXtq' : MemLp (fun ω => X ω - Xb ω) (ENNReal.ofReal q') P := hXq'.sub hXbq'
    have hB := abs_integral_mul_sub_mean_le_holder hq h1ltq' hqq'inv hXtq' hZmem
    have hXr_int : Integrable (fun ω => |X ω| ^ r) P := by
      have := hXmem.integrable_norm_rpow hrEne hrET
      simpa only [Real.norm_eq_abs, hrtoReal] using this
    have hXt_rpow_int : Integrable (fun ω => |X ω - Xb ω| ^ q') P := by
      have := hXtq'.integrable_norm_rpow
        (by simp only [Ne, ENNReal.ofReal_eq_zero, not_le]; exact hq'0) ENNReal.ofReal_ne_top
      simpa only [Real.norm_eq_abs, ENNReal.toReal_ofReal hq'0.le] using this
    have hXt_moment_nonneg : 0 ≤ ∫ ω, |X ω - Xb ω| ^ q' ∂P :=
      integral_nonneg (fun ω => Real.rpow_nonneg (abs_nonneg _) _)
    have htail_moment : ∫ ω, |X ω - Xb ω| ^ q' ∂P ≤ D₁ ^ (q' - r) * ∫ ω, |X ω| ^ r ∂P := by
      rw [← integral_const_mul]
      apply integral_mono_ae hXt_rpow_int (hXr_int.const_mul _)
      filter_upwards with ω
      simpa only [hXbdef] using abs_sub_trunc_rpow_le hq'0 hq'ler hD₁pos (X ω)
    have hNXt_bound : (∫ ω, |X ω - Xb ω| ^ q' ∂P) ^ q'⁻¹
        ≤ (D₁ ^ (q' - r) * ∫ ω, |X ω| ^ r ∂P) ^ q'⁻¹ :=
      Real.rpow_le_rpow hXt_moment_nonneg htail_moment (le_of_lt (inv_pos.mpr hq'0))
    have hBval : (D₁ ^ (q' - r) * ∫ ω, |X ω| ^ r ∂P) ^ q'⁻¹
        = MX * (alphaDep m₁ m₂ P) ^ (1 - r⁻¹ - q⁻¹) := by
      have harn : 0 ≤ (alphaDep m₁ m₂ P) ^ (-(r⁻¹)) := Real.rpow_nonneg hα.le _
      rw [← hMXr, hD₁def, Real.mul_rpow hMX0 harn, ← Real.rpow_mul hα.le,
        show MX ^ (q' - r) * (alphaDep m₁ m₂ P) ^ (-(r⁻¹) * (q' - r)) * MX ^ r
          = (MX ^ (q' - r) * MX ^ r) * (alphaDep m₁ m₂ P) ^ (-(r⁻¹) * (q' - r)) from by ring,
        ← Real.rpow_add hMXpos, show (q' - r) + r = q' from by ring,
        Real.mul_rpow (Real.rpow_nonneg hMXpos.le _) (Real.rpow_nonneg hα.le _),
        ← Real.rpow_mul hMXpos.le, ← Real.rpow_mul hα.le,
        show q' * q'⁻¹ = 1 from mul_inv_cancel₀ hq'ne, Real.rpow_one,
        show (-(r⁻¹) * (q' - r)) * q'⁻¹ = 1 - r⁻¹ - q⁻¹ from by rw [hq'def]; field_simp; ring]
    have htermB : |∫ ω, (X ω - Xb ω) * (Z ω - P[Z]) ∂P|
        ≤ 2 * (MX * (alphaDep m₁ m₂ P) ^ (1 - r⁻¹ - q⁻¹)) * MZ := by
      have hNXt : (∫ ω, |X ω - Xb ω| ^ q' ∂P) ^ q'⁻¹
          ≤ MX * (alphaDep m₁ m₂ P) ^ (1 - r⁻¹ - q⁻¹) := hNXt_bound.trans_eq hBval
      calc |∫ ω, (X ω - Xb ω) * (Z ω - P[Z]) ∂P|
          ≤ 2 * (∫ ω, |X ω - Xb ω| ^ q' ∂P) ^ q'⁻¹ * (∫ ω, |Z ω| ^ q ∂P) ^ q⁻¹ := hB
        _ = 2 * (∫ ω, |X ω - Xb ω| ^ q' ∂P) ^ q'⁻¹ * MZ := by rw [← hMZeq]
        _ ≤ 2 * (MX * (alphaDep m₁ m₂ P) ^ (1 - r⁻¹ - q⁻¹)) * MZ := by
            apply mul_le_mul_of_nonneg_right _ hMZ0
            exact mul_le_mul_of_nonneg_left hNXt (by norm_num)
    rw [hcov_eq, hsplit_int]
    calc |(∫ ω, Xb ω * (Z ω - P[Z]) ∂P) + ∫ ω, (X ω - Xb ω) * (Z ω - P[Z]) ∂P|
        ≤ |∫ ω, Xb ω * (Z ω - P[Z]) ∂P| + |∫ ω, (X ω - Xb ω) * (Z ω - P[Z]) ∂P| := abs_add_le _ _
      _ ≤ D₁ * (6 * MZ * (alphaDep m₁ m₂ P) ^ (1 - q⁻¹))
            + 2 * (MX * (alphaDep m₁ m₂ P) ^ (1 - r⁻¹ - q⁻¹)) * MZ := add_le_add hA htermB
      _ = 8 * MX * MZ * (alphaDep m₁ m₂ P) ^ (1 - r⁻¹ - q⁻¹) := by rw [hAval]; ring

end CovarianceInequalities

end ProbabilityTheory
