import HansenEconometrics.FDist
import HansenEconometrics.LinearAlgebraUtils
import HansenEconometrics.AsymptoticUtils

/-!
# Chapter 11 — matrix-normal and Wishart wrappers

This file provides support notation for the Chapter 11 matrix-normal appendix.
The Wishart law is represented as the push-forward law of a matrix quadratic
form. The law lemmas include non-tautological push-forward bridges for
cross-products, inverse-Wishart scalar forms, and Hotelling's statistic, plus
compatibility projections for the exact textbook laws. They do not yet derive
Hansen Theorems 11.10--11.12 from primitive normal/Wishart assumptions.
-/

open MeasureTheory ProbabilityTheory
open scoped Matrix Matrix.Norms.Elementwise

namespace HansenEconometrics

open Matrix

@[reducible]
private noncomputable def matrixBorelMeasurableSpaceInst
    {ι κ : Type*} [Fintype ι] [Fintype κ] :
    MeasurableSpace (Matrix ι κ ℝ) :=
  matrixBorelMeasurableSpace ι κ

attribute [local instance] matrixBorelMeasurableSpaceInst

private lemma matrixBorelSpaceInst
    {ι κ : Type*} [Fintype ι] [Fintype κ] :
    @BorelSpace (Matrix ι κ ℝ) _ (matrixBorelMeasurableSpaceInst (ι := ι) (κ := κ)) :=
  matrixBorelSpace ι κ

attribute [local instance] matrixBorelSpaceInst

variable {Ω n m : Type*}
variable [MeasurableSpace Ω] {μ : Measure Ω}
variable [Fintype n] [Fintype m] [DecidableEq n] [DecidableEq m]

/-- Matrix quadratic form `Y'Y`. -/
noncomputable def matrixCrossProduct (Y : Matrix n m ℝ) : Matrix m m ℝ :=
  Yᵀ * Y

/-- Wishart law generated by a matrix-valued sampling law. -/
noncomputable def wishartMatrixLaw
    (Ylaw : Measure (Matrix n m ℝ)) : Measure (Matrix m m ℝ) :=
  Ylaw.map matrixCrossProduct

/-- Scaled Wishart law, used for covariance matrices such as `(n-1)⁻¹ W`. -/
noncomputable def scaledWishartMatrixLaw
    (c : ℝ) (Ylaw : Measure (Matrix n m ℝ)) : Measure (Matrix m m ℝ) :=
  (wishartMatrixLaw Ylaw).map fun W => c • W

/-- Scalar inverse-Wishart linear form in Hansen Theorem 11.11. -/
noncomputable def inverseWishartLinearForm
    (α : m → ℝ) (W : Matrix m m ℝ) : ℝ :=
  (α ⬝ᵥ (W⁻¹ *ᵥ α))⁻¹

/-- Hotelling's `T²` statistic. -/
noncomputable def hotellingT2
    (root : ℝ) (Ybar μ0 : m → ℝ) (Shat : Matrix m m ℝ) : ℝ :=
  root * ((Ybar - μ0) ⬝ᵥ (Shat⁻¹ *ᵥ (Ybar - μ0)))

omit [DecidableEq n] [DecidableEq m] in
/-- A matrix cross-product has the Wishart push-forward law generated by the
law of the underlying sample matrix. -/
theorem matrixCrossProduct_hasLaw_wishartMatrixLaw
    (Y : Ω → Matrix n m ℝ) (Ylaw : Measure (Matrix n m ℝ))
    (hY : HasLaw Y Ylaw μ) :
    HasLaw (fun ω => matrixCrossProduct (Y ω)) (wishartMatrixLaw Ylaw) μ := by
  let hmap : HasLaw matrixCrossProduct (wishartMatrixLaw Ylaw) Ylaw :=
    ⟨by
      change AEMeasurable (fun Y : Matrix n m ℝ => Yᵀ * Y) Ylaw
      fun_prop, rfl⟩
  exact hmap.comp hY

omit [DecidableEq n] [DecidableEq m] in
/-- Scaling a matrix cross-product transfers the Wishart push-forward law to
the corresponding scaled Wishart law. -/
theorem scaledMatrixCrossProduct_hasLaw_scaledWishartMatrixLaw
    (Y : Ω → Matrix n m ℝ) (Ylaw : Measure (Matrix n m ℝ)) (c : ℝ)
    (hY : HasLaw Y Ylaw μ) :
    HasLaw (fun ω => c • matrixCrossProduct (Y ω)) (scaledWishartMatrixLaw c Ylaw) μ := by
  let hscale : HasLaw (fun W : Matrix m m ℝ => c • W)
      (scaledWishartMatrixLaw c Ylaw) (wishartMatrixLaw Ylaw) :=
    ⟨by fun_prop, rfl⟩
  exact hscale.comp (matrixCrossProduct_hasLaw_wishartMatrixLaw Y Ylaw hY)

omit [DecidableEq n] [DecidableEq m] in
/-- Sample covariance law from a scaled cross-product representation.

This is the theorem-facing bridge for Hansen Theorem 11.10 once the centered
normal sample matrix `Y` and the algebraic identity
`S = c • Y'Y` have been supplied. -/
theorem sampleCovariance_hasLaw_scaledWishartMatrixLaw_of_crossProduct
    (Shat : Ω → Matrix m m ℝ) (Y : Ω → Matrix n m ℝ)
    (Ylaw : Measure (Matrix n m ℝ)) (c : ℝ)
    (hY : HasLaw Y Ylaw μ)
    (hShat : Shat =ᵐ[μ] fun ω => c • matrixCrossProduct (Y ω)) :
    HasLaw Shat (scaledWishartMatrixLaw c Ylaw) μ :=
  (scaledMatrixCrossProduct_hasLaw_scaledWishartMatrixLaw Y Ylaw c hY).congr hShat

/-- Any inverse-Wishart linear-form law can be obtained as the push-forward of
the matrix law through Hansen's scalar map. -/
theorem inverseWishartLinearForm_hasLaw_map
    (W : Ω → Matrix m m ℝ) (Wlaw : Measure (Matrix m m ℝ)) (α : m → ℝ)
    (hW : HasLaw W Wlaw μ) :
    HasLaw (fun ω => inverseWishartLinearForm α (W ω))
      (Wlaw.map (inverseWishartLinearForm α)) μ := by
  have hInv : AEStronglyMeasurable (fun W : Matrix m m ℝ => W⁻¹) Wlaw :=
    aestronglyMeasurable_matrix_inv aestronglyMeasurable_id
  have hVec : AEStronglyMeasurable (fun W : Matrix m m ℝ => W⁻¹ *ᵥ α) Wlaw :=
    (Continuous.matrix_mulVec continuous_fst continuous_snd).comp_aestronglyMeasurable
      (hInv.prodMk aestronglyMeasurable_const)
  have hQuad : AEStronglyMeasurable
      (fun W : Matrix m m ℝ => α ⬝ᵥ (W⁻¹ *ᵥ α)) Wlaw := by
    have hsum : AEStronglyMeasurable
        (∑ i, fun W : Matrix m m ℝ => α i * (W⁻¹ *ᵥ α) i) Wlaw :=
      Finset.aestronglyMeasurable_sum Finset.univ
      (fun i _ => aestronglyMeasurable_const.mul
        ((continuous_apply i).comp_aestronglyMeasurable hVec))
    change AEStronglyMeasurable
      (fun W : Matrix m m ℝ => ∑ i, α i * (W⁻¹ *ᵥ α) i) Wlaw
    convert hsum using 1
    ext W
    simp only [Finset.sum_apply]
  let hmap : HasLaw (inverseWishartLinearForm α)
      (Wlaw.map (inverseWishartLinearForm α)) Wlaw :=
    ⟨by
      change AEMeasurable
        (fun W : Matrix m m ℝ => (α ⬝ᵥ (W⁻¹ *ᵥ α))⁻¹) Wlaw
      exact hQuad.aemeasurable.inv, rfl⟩
  exact hmap.comp hW

/-- Inverse-Wishart scalar-form chi-square law from a proved push-forward
identity. This is the reusable bridge for Hansen Theorem 11.11: once the
inverse-Wishart matrix law is known and its scalar map is identified with the
right chi-square law, the random-variable statement follows. -/
theorem inverseWishartLinearForm_hasLaw_chiSquared_of_map_eq
    (W : Ω → Matrix m m ℝ) (Wlaw : Measure (Matrix m m ℝ))
    (α : m → ℝ) (df : ℕ)
    (hW : HasLaw W Wlaw μ)
    (hmap : Wlaw.map (inverseWishartLinearForm α) = chiSquared df) :
    HasLaw (fun ω => inverseWishartLinearForm α (W ω)) (chiSquared df) μ := by
  rw [← hmap]
  exact inverseWishartLinearForm_hasLaw_map W Wlaw α hW

/-- Hotelling's `T²` law as a push-forward of the joint law of the sample mean
and sample covariance. -/
theorem hotellingT2_hasLaw_map
    (Z : Ω → (m → ℝ) × Matrix m m ℝ)
    (Zlaw : Measure ((m → ℝ) × Matrix m m ℝ))
    (root : ℝ) (μ0 : m → ℝ) (hZ : HasLaw Z Zlaw μ) :
    HasLaw (fun ω => hotellingT2 root (Z ω).1 μ0 (Z ω).2)
      (Zlaw.map fun z => hotellingT2 root z.1 μ0 z.2) μ := by
  have hShat : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ => z.2) Zlaw :=
    continuous_snd.aestronglyMeasurable
  have hShatInv : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ => z.2⁻¹) Zlaw :=
    aestronglyMeasurable_matrix_inv hShat
  have hDiff : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ => z.1 - μ0) Zlaw :=
    continuous_fst.aestronglyMeasurable.sub aestronglyMeasurable_const
  have hVec : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ => z.2⁻¹ *ᵥ (z.1 - μ0)) Zlaw :=
    (Continuous.matrix_mulVec continuous_fst continuous_snd).comp_aestronglyMeasurable
      (hShatInv.prodMk hDiff)
  have hQuad : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ =>
        (z.1 - μ0) ⬝ᵥ (z.2⁻¹ *ᵥ (z.1 - μ0))) Zlaw := by
    have hsum : AEStronglyMeasurable
        (∑ i, fun z : (m → ℝ) × Matrix m m ℝ =>
          (z.1 - μ0) i * (z.2⁻¹ *ᵥ (z.1 - μ0)) i) Zlaw :=
      Finset.aestronglyMeasurable_sum Finset.univ
      (fun i _ =>
        ((continuous_apply i).comp_aestronglyMeasurable hDiff).mul
          ((continuous_apply i).comp_aestronglyMeasurable hVec))
    change AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ =>
        ∑ i, (z.1 - μ0) i * (z.2⁻¹ *ᵥ (z.1 - μ0)) i) Zlaw
    convert hsum using 1
    ext z
    simp only [Finset.sum_apply]
  let hmap : HasLaw (fun z : (m → ℝ) × Matrix m m ℝ => hotellingT2 root z.1 μ0 z.2)
      (Zlaw.map fun z => hotellingT2 root z.1 μ0 z.2) Zlaw :=
    ⟨by
      change AEMeasurable
        (fun z : (m → ℝ) × Matrix m m ℝ =>
          root * ((z.1 - μ0) ⬝ᵥ (z.2⁻¹ *ᵥ (z.1 - μ0)))) Zlaw
      exact hQuad.aemeasurable.const_mul root, rfl⟩
  exact hmap.comp hZ

/-- Scaled-F bridge for Hotelling's `T²` statistic.

If a Hotelling statistic has been algebraically reduced to `scale` times a
ratio of two independent chi-square variates divided by their degrees of
freedom, then it has the corresponding scaled classical F law. -/
theorem hotellingT2_hasLaw_scaledFDist_of_chiSquared_ratio
    {U V T2 : Ω → ℝ} {q ν : ℕ} (scale : ℝ)
    (hq : 0 < q) (hν : 0 < ν)
    (hU : HasLaw U (chiSquared q) μ)
    (hV : HasLaw V (chiSquared ν) μ)
    (hInd : U ⟂ᵢ[μ] V)
    (hT2 : T2 =ᵐ[μ] fun ω => scale * ((U ω / (q : ℝ)) / (V ω / (ν : ℝ)))) :
    HasLaw T2 ((classicalFDist q ν).map fun x => scale * x) μ := by
  have hRatio :=
    hasLaw_ratio_chiSquared_fDist (μ := μ) hq hν hU hV hInd
  rw [fDist_eq_classicalFDist hq hν] at hRatio
  let hScale : HasLaw (fun x : ℝ => scale * x)
      ((classicalFDist q ν).map fun x => scale * x) (classicalFDist q ν) :=
    ⟨by fun_prop, rfl⟩
  have hScaled : HasLaw
      (fun ω => scale * ((U ω / (q : ℝ)) / (V ω / (ν : ℝ))))
      ((classicalFDist q ν).map fun x => scale * x) μ := by
    simpa [Function.comp_def] using hScale.comp hRatio
  exact hScaled.congr hT2

omit [DecidableEq n] [DecidableEq m] in
/-- Interface projection for a sample covariance with a scaled Wishart law. -/
theorem sampleCovariance_hasLaw_from_wishartInterface
    (Shat : Ω → Matrix m m ℝ) (Ylaw : Measure (Matrix n m ℝ)) (c : ℝ)
    (h : HasLaw Shat (scaledWishartMatrixLaw c Ylaw) μ) :
    HasLaw Shat (scaledWishartMatrixLaw c Ylaw) μ :=
  h

/-- Interface projection for an inverse-Wishart linear-form chi-square law. -/
theorem inverseWishartLinearForm_hasLaw_from_interface
    (W : Ω → Matrix m m ℝ) (α : m → ℝ) (df : ℕ)
    (h : HasLaw (fun ω => inverseWishartLinearForm α (W ω)) (chiSquared df) μ) :
    HasLaw (fun ω => inverseWishartLinearForm α (W ω)) (chiSquared df) μ :=
  h

/-- Interface projection for Hotelling's `T²` scaled F law. -/
theorem hotellingT2_hasLaw_from_interface
    (T2 : Ω → ℝ) (scale : ℝ) (q ν : ℕ)
    (h : HasLaw T2 ((classicalFDist q ν).map fun x => scale * x) μ) :
    HasLaw T2 ((classicalFDist q ν).map fun x => scale * x) μ :=
  h

end HansenEconometrics
