import HansenEconometrics.FDist
import HansenEconometrics.LinearAlgebraUtils
import HansenEconometrics.MultivariateNormal
import HansenEconometrics.AsymptoticUtils

/-!
# Chapter 11 — matrix-normal and Wishart wrappers

This file provides support notation for the Chapter 11 matrix-normal appendix.
The Wishart law is represented as the push-forward law of a matrix quadratic
form. The law lemmas include non-tautological push-forward bridges for
cross-products, inverse-Wishart scalar forms, and Hotelling's statistic, plus
compatibility projections for the exact textbook laws. They do not yet derive
Hansen Theorems 11.10--11.12 from primitive normal/Wishart assumptions.
-/

open MeasureTheory ProbabilityTheory
open scoped Matrix Matrix.Norms.Elementwise

namespace HansenEconometrics

open Matrix

@[reducible]
private noncomputable def matrixBorelMeasurableSpaceInst
    {ι κ : Type*} [Fintype ι] [Fintype κ] :
    MeasurableSpace (Matrix ι κ ℝ) :=
  matrixBorelMeasurableSpace ι κ

attribute [local instance] matrixBorelMeasurableSpaceInst

private lemma matrixBorelSpaceInst
    {ι κ : Type*} [Fintype ι] [Fintype κ] :
    @BorelSpace (Matrix ι κ ℝ) _ (matrixBorelMeasurableSpaceInst (ι := ι) (κ := κ)) :=
  matrixBorelSpace ι κ

attribute [local instance] matrixBorelSpaceInst

variable {Ω n m : Type*}
variable [MeasurableSpace Ω] {μ : Measure Ω}
variable [Fintype n] [Fintype m] [DecidableEq n] [DecidableEq m]

/-- Matrix quadratic form `Y'Y`. -/
noncomputable def matrixCrossProduct (Y : Matrix n m ℝ) : Matrix m m ℝ :=
  Yᵀ * Y

/-- Wishart law generated by a matrix-valued sampling law. -/
noncomputable def wishartMatrixLaw
    (Ylaw : Measure (Matrix n m ℝ)) : Measure (Matrix m m ℝ) :=
  Ylaw.map matrixCrossProduct

/-- Scaled Wishart law, used for covariance matrices such as `(n-1)⁻¹ W`. -/
noncomputable def scaledWishartMatrixLaw
    (c : ℝ) (Ylaw : Measure (Matrix n m ℝ)) : Measure (Matrix m m ℝ) :=
  (wishartMatrixLaw Ylaw).map fun W => c • W

/-- Row law for a vector-valued Gaussian observation, represented on plain
functions `m → ℝ` rather than `EuclideanSpace ℝ m`. -/
noncomputable def rowGaussianLaw
    (mean : m → ℝ) (Sigma : Matrix m m ℝ) : Measure (m → ℝ) :=
  (multivariateGaussian (WithLp.toLp 2 mean) Sigma).map
    fun z : EuclideanSpace ℝ m => z.ofLp

/-- Product law for iid Gaussian rows of a random matrix. This is the
Hansen-facing matrix-normal sampling law used by the Wishart surface. -/
noncomputable def iidMatrixGaussianLaw
    (mean : m → ℝ) (Sigma : Matrix m m ℝ) : Measure (Matrix n m ℝ) :=
  ((Measure.pi fun _ : n => rowGaussianLaw mean Sigma) : Measure (n → m → ℝ)).map
    fun Y : n → m → ℝ => (Y : Matrix n m ℝ)

/-- Hansen Wishart law `W_m(n, Σ)`, represented as the cross-product
push-forward of iid centered Gaussian rows. -/
noncomputable def wishartLaw (Sigma : Matrix m m ℝ) : Measure (Matrix m m ℝ) :=
  wishartMatrixLaw (iidMatrixGaussianLaw (n := n) (m := m) (0 : m → ℝ) Sigma)

/-- Hansen scaled Wishart law, used for sample covariance matrices. -/
noncomputable def scaledWishartLaw
    (c : ℝ) (Sigma : Matrix m m ℝ) : Measure (Matrix m m ℝ) :=
  scaledWishartMatrixLaw c
    (iidMatrixGaussianLaw (n := n) (m := m) (0 : m → ℝ) Sigma)

/-- Scalar inverse-Wishart linear form in Hansen Theorem 11.11. -/
noncomputable def inverseWishartLinearForm
    (α : m → ℝ) (W : Matrix m m ℝ) : ℝ :=
  (α ⬝ᵥ (W⁻¹ *ᵥ α))⁻¹

/-- Hansen's scaled inverse-Wishart linear form
`(α'Σ⁻¹α) / (α'W⁻¹α)`. -/
noncomputable def inverseWishartScaledLinearForm
    (Sigma : Matrix m m ℝ) (α : m → ℝ) (W : Matrix m m ℝ) : ℝ :=
  (α ⬝ᵥ (Sigma⁻¹ *ᵥ α)) * inverseWishartLinearForm α W

/-- Hotelling's `T²` statistic. -/
noncomputable def hotellingT2
    (root : ℝ) (Ybar μ0 : m → ℝ) (Shat : Matrix m m ℝ) : ℝ :=
  root * ((Ybar - μ0) ⬝ᵥ (Shat⁻¹ *ᵥ (Ybar - μ0)))

omit [DecidableEq n] [DecidableEq m] in
/-- Sample mean vector for rows indexed by observations. -/
noncomputable def sampleMeanMatrix (Y : n → m → ℝ) : m → ℝ :=
  (Fintype.card n : ℝ)⁻¹ • ∑ i : n, Y i

omit [DecidableEq n] [DecidableEq m] in
/-- Centered sample-row matrix `Yᵢ - Ȳ`. -/
noncomputable def centeredSampleMatrix (Y : n → m → ℝ) : Matrix n m ℝ :=
  fun i a => Y i a - sampleMeanMatrix Y a

omit [DecidableEq n] [DecidableEq m] in
/-- Bias-corrected sample covariance matrix `(n-1)⁻¹∑(Yᵢ-Ȳ)(Yᵢ-Ȳ)'`. -/
noncomputable def sampleCovarianceMatrix (Y : n → m → ℝ) : Matrix m m ℝ :=
  ((Fintype.card n - 1 : ℝ)⁻¹) • matrixCrossProduct (centeredSampleMatrix Y)

omit [DecidableEq n] [DecidableEq m] in
/-- Hansen's Hotelling statistic
`n(Ȳ-μ₀)'S⁻¹(Ȳ-μ₀)` built from the sample mean and sample covariance. -/
noncomputable def hotellingT2Sample (Y : n → m → ℝ) (μ0 : m → ℝ) : ℝ :=
  hotellingT2 (Fintype.card n : ℝ) (sampleMeanMatrix Y) μ0 (sampleCovarianceMatrix Y)

omit [DecidableEq n] [DecidableEq m] in
/-- Hansen's fixed Hotelling scale `m(n-1)/(n-m)` for the `F(m,n-m)` law. -/
noncomputable def hotellingT2HansenScale : ℝ :=
  ((Fintype.card m : ℝ) * ((Fintype.card n : ℝ) - 1)) /
    ((Fintype.card n : ℝ) - (Fintype.card m : ℝ))

omit [Fintype m] [DecidableEq n] [DecidableEq m] in
/-- Coordinate form of the bias-corrected sample covariance. -/
theorem sampleCovarianceMatrix_apply
    (Y : n → m → ℝ) (a b : m) :
    sampleCovarianceMatrix Y a b =
      ((Fintype.card n - 1 : ℝ)⁻¹) *
        ∑ i : n, (Y i a - sampleMeanMatrix Y a) *
          (Y i b - sampleMeanMatrix Y b) := by
  simp [sampleCovarianceMatrix, matrixCrossProduct, centeredSampleMatrix, Matrix.mul_apply,
    smul_eq_mul]

omit [DecidableEq n] [DecidableEq m] in
/-- A matrix cross-product has the Wishart push-forward law generated by the
law of the underlying sample matrix. -/
theorem matrixCrossProduct_hasLaw_wishartMatrixLaw
    (Y : Ω → Matrix n m ℝ) (Ylaw : Measure (Matrix n m ℝ))
    (hY : HasLaw Y Ylaw μ) :
    HasLaw (fun ω => matrixCrossProduct (Y ω)) (wishartMatrixLaw Ylaw) μ := by
  let hmap : HasLaw matrixCrossProduct (wishartMatrixLaw Ylaw) Ylaw :=
    ⟨by
      change AEMeasurable (fun Y : Matrix n m ℝ => Yᵀ * Y) Ylaw
      fun_prop, rfl⟩
  exact hmap.comp hY

omit [DecidableEq n] [DecidableEq m] in
/-- Scaling a matrix cross-product transfers the Wishart push-forward law to
the corresponding scaled Wishart law. -/
theorem scaledMatrixCrossProduct_hasLaw_scaledWishartMatrixLaw
    (Y : Ω → Matrix n m ℝ) (Ylaw : Measure (Matrix n m ℝ)) (c : ℝ)
    (hY : HasLaw Y Ylaw μ) :
    HasLaw (fun ω => c • matrixCrossProduct (Y ω)) (scaledWishartMatrixLaw c Ylaw) μ := by
  let hscale : HasLaw (fun W : Matrix m m ℝ => c • W)
      (scaledWishartMatrixLaw c Ylaw) (wishartMatrixLaw Ylaw) :=
    ⟨by fun_prop, rfl⟩
  exact hscale.comp (matrixCrossProduct_hasLaw_wishartMatrixLaw Y Ylaw hY)

omit [DecidableEq n] in
/-- Hansen Theorem 11.10 Wishart cross-product surface.

If a sample matrix has iid centered Gaussian row law with covariance `Σ`, then
its cross-product has the Hansen Wishart law `W_m(n,Σ)`. -/
theorem matrixCrossProduct_hasLaw_wishartLaw
    (Y : Ω → Matrix n m ℝ) (Sigma : Matrix m m ℝ)
    (hY : HasLaw Y
      (iidMatrixGaussianLaw (n := n) (m := m) (0 : m → ℝ) Sigma) μ) :
    HasLaw (fun ω => matrixCrossProduct (Y ω)) (wishartLaw (n := n) Sigma) μ := by
  simpa [wishartLaw] using
    matrixCrossProduct_hasLaw_wishartMatrixLaw
      (Y := Y)
      (Ylaw := iidMatrixGaussianLaw (n := n) (m := m) (0 : m → ℝ) Sigma)
      hY

omit [DecidableEq n] in
/-- Scaled Hansen-Wishart cross-product surface. -/
theorem scaledMatrixCrossProduct_hasLaw_scaledWishartLaw
    (Y : Ω → Matrix n m ℝ) (Sigma : Matrix m m ℝ) (c : ℝ)
    (hY : HasLaw Y
      (iidMatrixGaussianLaw (n := n) (m := m) (0 : m → ℝ) Sigma) μ) :
    HasLaw (fun ω => c • matrixCrossProduct (Y ω))
      (scaledWishartLaw (n := n) c Sigma) μ := by
  simpa [scaledWishartLaw] using
    scaledMatrixCrossProduct_hasLaw_scaledWishartMatrixLaw
      (Y := Y)
      (Ylaw := iidMatrixGaussianLaw (n := n) (m := m) (0 : m → ℝ) Sigma)
      (c := c) hY

omit [DecidableEq n] [DecidableEq m] in
/-- Sample covariance law from a scaled cross-product representation.

This is the theorem-facing bridge for Hansen Theorem 11.10 once the centered
normal sample matrix `Y` and the algebraic identity
`S = c • Y'Y` have been supplied. -/
theorem sampleCovariance_hasLaw_scaledWishartMatrixLaw_of_crossProduct
    (Shat : Ω → Matrix m m ℝ) (Y : Ω → Matrix n m ℝ)
    (Ylaw : Measure (Matrix n m ℝ)) (c : ℝ)
    (hY : HasLaw Y Ylaw μ)
    (hShat : Shat =ᵐ[μ] fun ω => c • matrixCrossProduct (Y ω)) :
    HasLaw Shat (scaledWishartMatrixLaw c Ylaw) μ :=
  (scaledMatrixCrossProduct_hasLaw_scaledWishartMatrixLaw Y Ylaw c hY).congr hShat

omit [DecidableEq n] [DecidableEq m] in
/-- Hansen Theorem 11.10 sample-covariance bridge.

Once the centered sample-row matrix has a matrix-normal sampling law, the
bias-corrected sample covariance has the corresponding scaled Wishart
push-forward law. -/
theorem sampleCovarianceMatrix_hasLaw_scaledWishartMatrixLaw_of_centeredRows
    (Y : Ω → n → m → ℝ) (Ylaw : Measure (Matrix n m ℝ))
    (hY : HasLaw (fun ω => centeredSampleMatrix (Y ω)) Ylaw μ) :
    HasLaw (fun ω => sampleCovarianceMatrix (Y ω))
      (scaledWishartMatrixLaw ((Fintype.card n - 1 : ℝ)⁻¹) Ylaw) μ := by
  simpa [sampleCovarianceMatrix] using
    scaledMatrixCrossProduct_hasLaw_scaledWishartMatrixLaw
      (Y := fun ω => centeredSampleMatrix (Y ω)) (Ylaw := Ylaw)
      (c := ((Fintype.card n - 1 : ℝ)⁻¹)) hY

omit [DecidableEq n] in
/-- Hansen Theorem 11.10 sample-covariance surface in Wishart notation.

Once the centered sample-row matrix has iid centered Gaussian row law with
covariance `Σ`, the bias-corrected sample covariance has the scaled Wishart law
`(n-1)⁻¹ W_m(n,Σ)` in the repository's finite-index notation. -/
theorem sampleCovarianceMatrix_hasLaw_scaledWishartLaw_of_centeredRows
    (Y : Ω → n → m → ℝ) (Sigma : Matrix m m ℝ)
    (hY : HasLaw (fun ω => centeredSampleMatrix (Y ω))
      (iidMatrixGaussianLaw (n := n) (m := m) (0 : m → ℝ) Sigma) μ) :
    HasLaw (fun ω => sampleCovarianceMatrix (Y ω))
      (scaledWishartLaw (n := n) ((Fintype.card n - 1 : ℝ)⁻¹) Sigma) μ := by
  simpa [scaledWishartLaw] using
    sampleCovarianceMatrix_hasLaw_scaledWishartMatrixLaw_of_centeredRows
      (Y := Y)
      (Ylaw := iidMatrixGaussianLaw (n := n) (m := m) (0 : m → ℝ) Sigma)
      hY

omit [DecidableEq n] in
/-- Hansen Theorem 11.10 sample-covariance bridge with the correct centered
sample degrees of freedom.

The centered residual matrix has rank `n - 1`; this theorem lets the proof use
an explicit `df`-row Gaussian representation of those centered rows rather than
incorrectly treating all `n` centered rows as iid. -/
theorem sampleCovarianceMatrix_hasLaw_scaledWishartLaw_of_centeredRows_df
    {df : Type*} [Fintype df]
    (Y : Ω → n → m → ℝ) (Z : Ω → Matrix df m ℝ) (Sigma : Matrix m m ℝ)
    (hZ : HasLaw Z
      (iidMatrixGaussianLaw (n := df) (m := m) (0 : m → ℝ) Sigma) μ)
    (hShat : (fun ω => sampleCovarianceMatrix (Y ω)) =ᵐ[μ]
      fun ω => ((Fintype.card n - 1 : ℝ)⁻¹) • matrixCrossProduct (Z ω)) :
    HasLaw (fun ω => sampleCovarianceMatrix (Y ω))
      (scaledWishartLaw (n := df) ((Fintype.card n - 1 : ℝ)⁻¹) Sigma) μ :=
  (scaledMatrixCrossProduct_hasLaw_scaledWishartLaw
    (Y := Z) (Sigma := Sigma) (c := ((Fintype.card n - 1 : ℝ)⁻¹)) hZ).congr hShat

/-- Any inverse-Wishart linear-form law can be obtained as the push-forward of
the matrix law through Hansen's scalar map. -/
theorem inverseWishartLinearForm_hasLaw_map
    (W : Ω → Matrix m m ℝ) (Wlaw : Measure (Matrix m m ℝ)) (α : m → ℝ)
    (hW : HasLaw W Wlaw μ) :
    HasLaw (fun ω => inverseWishartLinearForm α (W ω))
      (Wlaw.map (inverseWishartLinearForm α)) μ := by
  have hInv : AEStronglyMeasurable (fun W : Matrix m m ℝ => W⁻¹) Wlaw :=
    aestronglyMeasurable_matrix_inv aestronglyMeasurable_id
  have hVec : AEStronglyMeasurable (fun W : Matrix m m ℝ => W⁻¹ *ᵥ α) Wlaw :=
    (Continuous.matrix_mulVec continuous_fst continuous_snd).comp_aestronglyMeasurable
      (hInv.prodMk aestronglyMeasurable_const)
  have hQuad : AEStronglyMeasurable
      (fun W : Matrix m m ℝ => α ⬝ᵥ (W⁻¹ *ᵥ α)) Wlaw := by
    have hsum : AEStronglyMeasurable
        (∑ i, fun W : Matrix m m ℝ => α i * (W⁻¹ *ᵥ α) i) Wlaw :=
      Finset.aestronglyMeasurable_sum Finset.univ
      (fun i _ => aestronglyMeasurable_const.mul
        ((continuous_apply i).comp_aestronglyMeasurable hVec))
    change AEStronglyMeasurable
      (fun W : Matrix m m ℝ => ∑ i, α i * (W⁻¹ *ᵥ α) i) Wlaw
    convert hsum using 1
    ext W
    simp only [Finset.sum_apply]
  let hmap : HasLaw (inverseWishartLinearForm α)
      (Wlaw.map (inverseWishartLinearForm α)) Wlaw :=
    ⟨by
      change AEMeasurable
        (fun W : Matrix m m ℝ => (α ⬝ᵥ (W⁻¹ *ᵥ α))⁻¹) Wlaw
      exact hQuad.aemeasurable.inv, rfl⟩
  exact hmap.comp hW

/-- Inverse-Wishart scalar-form chi-square law from a proved push-forward
identity. This is the reusable bridge for Hansen Theorem 11.11: once the
inverse-Wishart matrix law is known and its scalar map is identified with the
right chi-square law, the random-variable statement follows. -/
theorem inverseWishartLinearForm_hasLaw_chiSquared_of_map_eq
    (W : Ω → Matrix m m ℝ) (Wlaw : Measure (Matrix m m ℝ))
    (α : m → ℝ) (df : ℕ)
    (hW : HasLaw W Wlaw μ)
    (hmap : Wlaw.map (inverseWishartLinearForm α) = chiSquared df) :
    HasLaw (fun ω => inverseWishartLinearForm α (W ω)) (chiSquared df) μ := by
  rw [← hmap]
  exact inverseWishartLinearForm_hasLaw_map W Wlaw α hW

private theorem inverseWishartLinearForm_aemeasurable
    (Wlaw : Measure (Matrix m m ℝ)) (α : m → ℝ) :
    AEMeasurable (inverseWishartLinearForm α) Wlaw := by
  have hId : HasLaw (fun W : Matrix m m ℝ => W) Wlaw Wlaw :=
    HasLaw.id
  exact (inverseWishartLinearForm_hasLaw_map
    (Ω := Matrix m m ℝ) (μ := Wlaw)
    (fun W : Matrix m m ℝ => W) Wlaw α hId).aemeasurable

/-- Hansen Theorem 11.11 scaled inverse-Wishart scalar form as a push-forward
of the matrix law. -/
theorem inverseWishartScaledLinearForm_hasLaw_map
    (W : Ω → Matrix m m ℝ) (Wlaw : Measure (Matrix m m ℝ))
    (Sigma : Matrix m m ℝ) (α : m → ℝ)
    (hW : HasLaw W Wlaw μ) :
    HasLaw (fun ω => inverseWishartScaledLinearForm Sigma α (W ω))
      (Wlaw.map (inverseWishartScaledLinearForm Sigma α)) μ := by
  let c : ℝ := α ⬝ᵥ (Sigma⁻¹ *ᵥ α)
  let hmap : HasLaw (inverseWishartScaledLinearForm Sigma α)
      (Wlaw.map (inverseWishartScaledLinearForm Sigma α)) Wlaw :=
    ⟨by
      change AEMeasurable (fun W : Matrix m m ℝ =>
        (α ⬝ᵥ (Sigma⁻¹ *ᵥ α)) * inverseWishartLinearForm α W) Wlaw
      exact (inverseWishartLinearForm_aemeasurable Wlaw α).const_mul
        (α ⬝ᵥ (Sigma⁻¹ *ᵥ α)), rfl⟩
  exact hmap.comp hW

/-- Hansen Theorem 11.11 scaled inverse-Wishart chi-square bridge.

The map identity is the remaining Schur-complement/inverse-Wishart content; the
random-variable law then follows without restating the measurability proof. -/
theorem inverseWishartScaledLinearForm_hasLaw_chiSquared_of_map_eq
    (W : Ω → Matrix m m ℝ) (Wlaw : Measure (Matrix m m ℝ))
    (Sigma : Matrix m m ℝ) (α : m → ℝ) (df : ℕ)
    (hW : HasLaw W Wlaw μ)
    (hmap : Wlaw.map (inverseWishartScaledLinearForm Sigma α) = chiSquared df) :
    HasLaw (fun ω => inverseWishartScaledLinearForm Sigma α (W ω)) (chiSquared df) μ := by
  rw [← hmap]
  exact inverseWishartScaledLinearForm_hasLaw_map W Wlaw Sigma α hW

omit [DecidableEq n] in
/-- Hansen Theorem 11.11 Wishart-law specialization.

For `W ∼ W_m(n,Σ)`, the scaled inverse-Wishart linear form has Hansen's
chi-square law once the Schur-complement push-forward identity has been proved
for the named `wishartLaw`. -/
theorem inverseWishartScaledLinearForm_hasLaw_chiSquared_of_wishartLaw_map_eq
    (W : Ω → Matrix m m ℝ) (Sigma : Matrix m m ℝ) (α : m → ℝ)
    (hW : HasLaw W (wishartLaw (n := n) Sigma) μ)
    (hmap : (wishartLaw (n := n) Sigma).map
        (inverseWishartScaledLinearForm Sigma α) =
      chiSquared (Fintype.card n - Fintype.card m + 1)) :
    HasLaw (fun ω => inverseWishartScaledLinearForm Sigma α (W ω))
      (chiSquared (Fintype.card n - Fintype.card m + 1)) μ :=
  inverseWishartScaledLinearForm_hasLaw_chiSquared_of_map_eq
    (W := W) (Wlaw := wishartLaw (n := n) Sigma)
    (Sigma := Sigma) (α := α)
    (df := Fintype.card n - Fintype.card m + 1) hW hmap

/-- Hotelling's `T²` law as a push-forward of the joint law of the sample mean
and sample covariance. -/
theorem hotellingT2_hasLaw_map
    (Z : Ω → (m → ℝ) × Matrix m m ℝ)
    (Zlaw : Measure ((m → ℝ) × Matrix m m ℝ))
    (root : ℝ) (μ0 : m → ℝ) (hZ : HasLaw Z Zlaw μ) :
    HasLaw (fun ω => hotellingT2 root (Z ω).1 μ0 (Z ω).2)
      (Zlaw.map fun z => hotellingT2 root z.1 μ0 z.2) μ := by
  have hShat : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ => z.2) Zlaw :=
    continuous_snd.aestronglyMeasurable
  have hShatInv : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ => z.2⁻¹) Zlaw :=
    aestronglyMeasurable_matrix_inv hShat
  have hDiff : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ => z.1 - μ0) Zlaw :=
    continuous_fst.aestronglyMeasurable.sub aestronglyMeasurable_const
  have hVec : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ => z.2⁻¹ *ᵥ (z.1 - μ0)) Zlaw :=
    (Continuous.matrix_mulVec continuous_fst continuous_snd).comp_aestronglyMeasurable
      (hShatInv.prodMk hDiff)
  have hQuad : AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ =>
        (z.1 - μ0) ⬝ᵥ (z.2⁻¹ *ᵥ (z.1 - μ0))) Zlaw := by
    have hsum : AEStronglyMeasurable
        (∑ i, fun z : (m → ℝ) × Matrix m m ℝ =>
          (z.1 - μ0) i * (z.2⁻¹ *ᵥ (z.1 - μ0)) i) Zlaw :=
      Finset.aestronglyMeasurable_sum Finset.univ
      (fun i _ =>
        ((continuous_apply i).comp_aestronglyMeasurable hDiff).mul
          ((continuous_apply i).comp_aestronglyMeasurable hVec))
    change AEStronglyMeasurable
      (fun z : (m → ℝ) × Matrix m m ℝ =>
        ∑ i, (z.1 - μ0) i * (z.2⁻¹ *ᵥ (z.1 - μ0)) i) Zlaw
    convert hsum using 1
    ext z
    simp only [Finset.sum_apply]
  let hmap : HasLaw (fun z : (m → ℝ) × Matrix m m ℝ => hotellingT2 root z.1 μ0 z.2)
      (Zlaw.map fun z => hotellingT2 root z.1 μ0 z.2) Zlaw :=
    ⟨by
      change AEMeasurable
        (fun z : (m → ℝ) × Matrix m m ℝ =>
          root * ((z.1 - μ0) ⬝ᵥ (z.2⁻¹ *ᵥ (z.1 - μ0)))) Zlaw
      exact hQuad.aemeasurable.const_mul root, rfl⟩
  exact hmap.comp hZ

omit [DecidableEq n] in
/-- Hansen Theorem 11.12 sample-statistic map bridge from the joint law of
`(Ȳ,S)`. -/
theorem hotellingT2Sample_hasLaw_map
    (Y : Ω → n → m → ℝ)
    (Zlaw : Measure ((m → ℝ) × Matrix m m ℝ)) (μ0 : m → ℝ)
    (hZ : HasLaw
      (fun ω => (sampleMeanMatrix (Y ω), sampleCovarianceMatrix (Y ω))) Zlaw μ) :
    HasLaw (fun ω => hotellingT2Sample (Y ω) μ0)
      (Zlaw.map fun z => hotellingT2 (Fintype.card n : ℝ) z.1 μ0 z.2) μ := by
  simpa [hotellingT2Sample] using
    hotellingT2_hasLaw_map
      (Z := fun ω => (sampleMeanMatrix (Y ω), sampleCovarianceMatrix (Y ω)))
      (Zlaw := Zlaw) (root := (Fintype.card n : ℝ)) (μ0 := μ0) hZ

/-- Scaled-F bridge for Hotelling's `T²` statistic.

If a Hotelling statistic has been algebraically reduced to `scale` times a
ratio of two independent chi-square variates divided by their degrees of
freedom, then it has the corresponding scaled classical F law. -/
theorem hotellingT2_hasLaw_scaledFDist_of_chiSquared_ratio
    {U V T2 : Ω → ℝ} {q ν : ℕ} (scale : ℝ)
    (hq : 0 < q) (hν : 0 < ν)
    (hU : HasLaw U (chiSquared q) μ)
    (hV : HasLaw V (chiSquared ν) μ)
    (hInd : U ⟂ᵢ[μ] V)
    (hT2 : T2 =ᵐ[μ] fun ω => scale * ((U ω / (q : ℝ)) / (V ω / (ν : ℝ)))) :
    HasLaw T2 ((classicalFDist q ν).map fun x => scale * x) μ := by
  have hRatio :=
    hasLaw_ratio_chiSquared_fDist (μ := μ) hq hν hU hV hInd
  rw [fDist_eq_classicalFDist hq hν] at hRatio
  let hScale : HasLaw (fun x : ℝ => scale * x)
      ((classicalFDist q ν).map fun x => scale * x) (classicalFDist q ν) :=
    ⟨by fun_prop, rfl⟩
  have hScaled : HasLaw
      (fun ω => scale * ((U ω / (q : ℝ)) / (V ω / (ν : ℝ))))
      ((classicalFDist q ν).map fun x => scale * x) μ := by
    simpa [Function.comp_def] using hScale.comp hRatio
  exact hScaled.congr hT2

omit [DecidableEq n] in
/-- Hansen Theorem 11.12 scaled-F bridge with the textbook degrees of freedom
and fixed Hotelling scale `m(n-1)/(n-m)`. -/
theorem hotellingT2Sample_hasLaw_hansen_scaledFDist_of_chiSquared_ratio
    (Y : Ω → n → m → ℝ) (μ0 : m → ℝ)
    {U V : Ω → ℝ}
    (hm : 0 < Fintype.card m) (hν : 0 < Fintype.card n - Fintype.card m)
    (hU : HasLaw U (chiSquared (Fintype.card m)) μ)
    (hV : HasLaw V (chiSquared (Fintype.card n - Fintype.card m)) μ)
    (hInd : U ⟂ᵢ[μ] V)
    (hT2 : (fun ω => hotellingT2Sample (Y ω) μ0) =ᵐ[μ]
      fun ω => hotellingT2HansenScale (n := n) (m := m) *
        ((U ω / (Fintype.card m : ℝ)) /
          (V ω / ((Fintype.card n - Fintype.card m : ℕ) : ℝ)))) :
    HasLaw (fun ω => hotellingT2Sample (Y ω) μ0)
      ((classicalFDist (Fintype.card m) (Fintype.card n - Fintype.card m)).map
        fun x => hotellingT2HansenScale (n := n) (m := m) * x) μ :=
  hotellingT2_hasLaw_scaledFDist_of_chiSquared_ratio
    (scale := hotellingT2HansenScale (n := n) (m := m))
    hm hν hU hV hInd hT2

omit [DecidableEq n] [DecidableEq m] in
/-- Interface projection for a sample covariance with a scaled Wishart law. -/
theorem sampleCovariance_hasLaw_from_wishartInterface
    (Shat : Ω → Matrix m m ℝ) (Ylaw : Measure (Matrix n m ℝ)) (c : ℝ)
    (h : HasLaw Shat (scaledWishartMatrixLaw c Ylaw) μ) :
    HasLaw Shat (scaledWishartMatrixLaw c Ylaw) μ :=
  h

/-- Interface projection for an inverse-Wishart linear-form chi-square law. -/
theorem inverseWishartLinearForm_hasLaw_from_interface
    (W : Ω → Matrix m m ℝ) (α : m → ℝ) (df : ℕ)
    (h : HasLaw (fun ω => inverseWishartLinearForm α (W ω)) (chiSquared df) μ) :
    HasLaw (fun ω => inverseWishartLinearForm α (W ω)) (chiSquared df) μ :=
  h

/-- Interface projection for the scaled inverse-Wishart linear form. -/
theorem inverseWishartScaledLinearForm_hasLaw_from_interface
    (W : Ω → Matrix m m ℝ) (Sigma : Matrix m m ℝ) (α : m → ℝ) (df : ℕ)
    (h : HasLaw (fun ω => inverseWishartScaledLinearForm Sigma α (W ω))
      (chiSquared df) μ) :
    HasLaw (fun ω => inverseWishartScaledLinearForm Sigma α (W ω)) (chiSquared df) μ :=
  h

/-- Interface projection for Hotelling's `T²` scaled F law. -/
theorem hotellingT2_hasLaw_from_interface
    (T2 : Ω → ℝ) (scale : ℝ) (q ν : ℕ)
    (h : HasLaw T2 ((classicalFDist q ν).map fun x => scale * x) μ) :
    HasLaw T2 ((classicalFDist q ν).map fun x => scale * x) μ :=
  h

end HansenEconometrics
