import HansenEconometrics.FDist
import HansenEconometrics.LinearAlgebraUtils

/-!
# Chapter 11 — matrix-normal and Wishart wrappers

This file provides support notation for the Chapter 11 matrix-normal appendix.
The Wishart law is represented as the push-forward law of a matrix quadratic
form. The law lemmas below project supplied law interfaces; they do not yet
derive Hansen Theorems 11.10--11.12 from primitive normal/Wishart assumptions.
-/

open MeasureTheory ProbabilityTheory
open scoped Matrix

namespace HansenEconometrics

open Matrix

@[reducible]
private noncomputable def matrixBorelMeasurableSpaceInst
    {ι κ : Type*} [Fintype ι] [Fintype κ] :
    MeasurableSpace (Matrix ι κ ℝ) :=
  matrixBorelMeasurableSpace ι κ

attribute [local instance] matrixBorelMeasurableSpaceInst

variable {Ω n m : Type*}
variable [MeasurableSpace Ω] {μ : Measure Ω}
variable [Fintype n] [Fintype m] [DecidableEq n] [DecidableEq m]

/-- Matrix quadratic form `Y'Y`. -/
noncomputable def matrixCrossProduct (Y : Matrix n m ℝ) : Matrix m m ℝ :=
  Yᵀ * Y

/-- Wishart law generated by a matrix-valued sampling law. -/
noncomputable def wishartMatrixLaw
    (Ylaw : Measure (Matrix n m ℝ)) : Measure (Matrix m m ℝ) :=
  Ylaw.map matrixCrossProduct

/-- Scaled Wishart law, used for covariance matrices such as `(n-1)⁻¹ W`. -/
noncomputable def scaledWishartMatrixLaw
    (c : ℝ) (Ylaw : Measure (Matrix n m ℝ)) : Measure (Matrix m m ℝ) :=
  (wishartMatrixLaw Ylaw).map fun W => c • W

/-- Scalar inverse-Wishart linear form in Hansen Theorem 11.11. -/
noncomputable def inverseWishartLinearForm
    (α : m → ℝ) (W : Matrix m m ℝ) : ℝ :=
  (α ⬝ᵥ (W⁻¹ *ᵥ α))⁻¹

/-- Hotelling's `T²` statistic. -/
noncomputable def hotellingT2
    (root : ℝ) (Ybar μ0 : m → ℝ) (Shat : Matrix m m ℝ) : ℝ :=
  root * ((Ybar - μ0) ⬝ᵥ (Shat⁻¹ *ᵥ (Ybar - μ0)))

omit [DecidableEq n] [DecidableEq m] in
/-- Interface projection for a sample covariance with a scaled Wishart law. -/
theorem sampleCovariance_hasLaw_from_wishartInterface
    (Shat : Ω → Matrix m m ℝ) (Ylaw : Measure (Matrix n m ℝ)) (c : ℝ)
    (h : HasLaw Shat (scaledWishartMatrixLaw c Ylaw) μ) :
    HasLaw Shat (scaledWishartMatrixLaw c Ylaw) μ :=
  h

/-- Interface projection for an inverse-Wishart linear-form chi-square law. -/
theorem inverseWishartLinearForm_hasLaw_from_interface
    (W : Ω → Matrix m m ℝ) (α : m → ℝ) (df : ℕ)
    (h : HasLaw (fun ω => inverseWishartLinearForm α (W ω)) (chiSquared df) μ) :
    HasLaw (fun ω => inverseWishartLinearForm α (W ω)) (chiSquared df) μ :=
  h

/-- Interface projection for Hotelling's `T²` scaled F law. -/
theorem hotellingT2_hasLaw_from_interface
    (T2 : Ω → ℝ) (scale : ℝ) (q ν : ℕ)
    (h : HasLaw T2 ((classicalFDist q ν).map fun x => scale * x) μ) :
    HasLaw T2 ((classicalFDist q ν).map fun x => scale * x) μ :=
  h

end HansenEconometrics
