import Lean
import Lean.Data.Json

/-!
# ExportDecls

Lean executable that walks the `HansenEconometrics` environment and emits a JSON
array of public declarations (theorems, defs, axioms) to stdout.

Each record is a JSON object with the following fields:

* `name`      : `String` — fully qualified declaration name.
* `namespace` : `String` — name's prefix (the enclosing namespace).
* `kind`      : `String` — one of `"theorem"`, `"def"`, `"axiom"`.
* `signature` : `String` — pretty-printed type.
* `docstring` : `String | null` — module docstring, if any.
* `file`      : `String` — module path with `/` separators (e.g. `HansenEconometrics/Chapter7.lean`).
* `line`      : `Number` — 1-based source line of the declaration's selection range.
* `chapter`   : `Number | null` — chapter number parsed from the module name, if any.
* `isPrivate` : `Bool` — whether the declaration is private.

Output is written to stdout; redirect into a file:
  `lake exe export_decls > /tmp/decls.json`

Downstream consumer: `scripts/build_stubs.py`.
-/

open Lean Elab Meta

namespace HansenExport

/-- Should the declaration be skipped because its name looks auto-generated?
We defer to `Name.isInternalDetail` from Lean core (which is maintained against
compiler internals), and additionally filter a few project-specific patterns
(`_proof_`, `_eqn_`, `_aux_`, `_cstage` substrings, and any name component
starting with `_`) for belt-and-suspenders coverage. -/
def isAutoGenerated (n : Name) : Bool :=
  if n.isInternalDetail then true
  else
    let badSubs : List String := ["_proof_", "_eqn_", "_aux_", "_cstage"]
    let rec go : Name → Bool
      | .anonymous => false
      | .num p _ => go p
      | .str p s =>
        if s.startsWith "_" then true
        else if badSubs.any (fun b => (s.splitOn b).length > 1) then true
        else go p
    go n

/-- Kind string for a `ConstantInfo`, or `none` if it should be skipped. -/
def kindString (ci : ConstantInfo) : Option String :=
  match ci with
  | .thmInfo _ => some "theorem"
  | .defnInfo _ => some "def"
  | .axiomInfo _ => some "axiom"
  | _ => none

/-- Parse the chapter integer from a module name's last component, if any. -/
def chapterOfModule (mod : Name) : Option Nat :=
  let last : String :=
    match mod with
    | .str _ s => s
    | _ => ""
  if last.startsWith "Chapter" then
    let rest := last.drop "Chapter".length
    -- take leading digits
    let digits := rest.takeWhile Char.isDigit
    if digits.isEmpty then none else digits.toNat?
  else
    none

/-- Convert a module name to a relative file path (slashes). -/
def moduleToPath (mod : Name) : String :=
  mod.toString.replace "." "/" ++ ".lean"

/-- Build a JSON record for a single declaration. Returns `none` if it should be skipped. -/
def mkRecord (env : Environment) (declName : Name) (ci : ConstantInfo) :
    MetaM (Option Json) := do
  let some kind := kindString ci | return none
  if isAutoGenerated declName then return none
  -- Find the module this decl came from
  let some modIdx := env.const2ModIdx.get? declName | return none
  let some modName := env.header.moduleNames[modIdx.toNat]? | return none
  -- Filter to HansenEconometrics
  let modStr := modName.toString
  unless modStr.startsWith "HansenEconometrics" do return none
  -- Pretty-print type
  let typeFmt ← Meta.ppExpr ci.type
  let signature := typeFmt.pretty
  -- Docstring
  let doc? ← Lean.findDocString? env declName
  -- Source line
  let ranges? ← Lean.findDeclarationRanges? declName
  let line : Nat := match ranges? with
    | some r => r.selectionRange.pos.line
    | none => 0
  let file := moduleToPath modName
  let nameSpace := declName.getPrefix
  let chapter := chapterOfModule modName
  let isPrivate := Lean.isPrivateName declName
  let fields : List (String × Json) := [
    ("name", Json.str declName.toString),
    ("namespace", Json.str nameSpace.toString),
    ("kind", Json.str kind),
    ("signature", Json.str signature),
    ("docstring", match doc? with | some d => Json.str d | none => Json.null),
    ("file", Json.str file),
    ("line", Json.num (JsonNumber.fromNat line)),
    ("chapter", match chapter with | some c => Json.num (JsonNumber.fromNat c) | none => Json.null),
    ("isPrivate", Json.bool isPrivate)
  ]
  return some (Json.mkObj fields)

unsafe def main (_args : List String) : IO UInt32 := do
  Lean.initSearchPath (← Lean.findSysroot)
  let env ← Lean.importModules
    (loadExts := false)
    (imports := #[{ module := `HansenEconometrics }])
    (opts := {})
  let action : MetaM (Array Json) := do
    let mut acc : Array Json := #[]
    for (declName, ci) in env.constants.toList do
      match ← mkRecord env declName ci with
      | some j => acc := acc.push j
      | none => pure ()
    return acc
  let eioRes : EIO Exception (Array Json) :=
    action.run'.run' { fileName := "<export_decls>", fileMap := default } { env := env }
  let records : Array Json ← match (← eioRes.toBaseIO) with
    | .ok a => pure a
    | .error e => throw (IO.userError s!"MetaM error: {← e.toMessageData.toString}")
  -- Sort by (file, line)
  let getKey (j : Json) : String × Nat :=
    let f := (j.getObjValAs? String "file").toOption.getD ""
    let l := (j.getObjValAs? Nat "line").toOption.getD 0
    (f, l)
  let sorted := Array.qsort records (fun a b =>
    let (fa, la) := getKey a
    let (fb, lb) := getKey b
    if fa = fb then la < lb else fa < fb)
  IO.println (Json.arr sorted).pretty
  return 0

end HansenExport

unsafe def main (args : List String) : IO UInt32 := HansenExport.main args
